"""Python SDK for Marmot."""

from marmot.auth import ENVIRONMENT_API_KEY, ENVIRONMENT_BEARER_TOKEN, Credential
from marmot.client import AuthenticatedApiClient
from marmot.config import ENVIRONMENT_HOST, ENVIRONMENT_MARMOT_CONTEXT
from marmot.errors import (
    AuthError,
    MarmotError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from marmot.generated import (
    AdminApi,
    AgentsApi,
    ApiClient,
    ApiException,
    AssetRulesApi,
    AssetsApi,
    AuthApi,
    Configuration,
    GlossaryApi,
    IngestionApi,
    LineageApi,
    MetricsApi,
    OwnersApi,
    PipelinesApi,
    PluginsApi,
    ProductsApi,
    RolesApi,
    RunsApi,
    SearchApi,
    ServiceAccountsApi,
    SsoApi,
    TeamsApi,
    UiApi,
    UsersApi,
)

__all__ = [
    "ENVIRONMENT_API_KEY",
    "ENVIRONMENT_BEARER_TOKEN",
    "ENVIRONMENT_HOST",
    "ENVIRONMENT_MARMOT_CONTEXT",
    "AdminApi",
    "AgentsApi",
    "ApiClient",
    "ApiException",
    "AssetRulesApi",
    "AssetsApi",
    "AuthApi",
    "AuthError",
    "AuthenticatedApiClient",
    "Configuration",
    "Credential",
    "GlossaryApi",
    "IngestionApi",
    "LineageApi",
    "MarmotError",
    "MetricsApi",
    "NotFoundError",
    "OwnersApi",
    "PipelinesApi",
    "PluginsApi",
    "ProductsApi",
    "RateLimitError",
    "RolesApi",
    "RunsApi",
    "SearchApi",
    "ServerError",
    "ServiceAccountsApi",
    "SsoApi",
    "TeamsApi",
    "UiApi",
    "UsersApi",
    "ValidationError",
]

__version__ = "0.4.0"
