// Code generated by go-swagger; DO NOT EDIT.

package agents

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new agents API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new agents API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new agents API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for agents API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAgentsAssetIDActivity(params *GetAgentsAssetIDActivityParams, opts ...ClientOption) (*GetAgentsAssetIDActivityOK, error)

	GetAgentsAssetIDRuns(params *GetAgentsAssetIDRunsParams, opts ...ClientOption) (*GetAgentsAssetIDRunsOK, error)

	GetAgentsAssetIDStats(params *GetAgentsAssetIDStatsParams, opts ...ClientOption) (*GetAgentsAssetIDStatsOK, error)

	PostAgentsRuns(params *PostAgentsRunsParams, opts ...ClientOption) (*PostAgentsRunsCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAgentsAssetIDActivity agents activity
*/
func (a *Client) GetAgentsAssetIDActivity(params *GetAgentsAssetIDActivityParams, opts ...ClientOption) (*GetAgentsAssetIDActivityOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAgentsAssetIDActivityParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAgentsAssetIDActivity",
		Method:             "GET",
		PathPattern:        "/agents/{asset_id}/activity",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAgentsAssetIDActivityReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAgentsAssetIDActivityOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAgentsAssetIDActivity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAgentsAssetIDRuns lists agent runs
*/
func (a *Client) GetAgentsAssetIDRuns(params *GetAgentsAssetIDRunsParams, opts ...ClientOption) (*GetAgentsAssetIDRunsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAgentsAssetIDRunsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAgentsAssetIDRuns",
		Method:             "GET",
		PathPattern:        "/agents/{asset_id}/runs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAgentsAssetIDRunsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAgentsAssetIDRunsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAgentsAssetIDRuns: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAgentsAssetIDStats agents stats
*/
func (a *Client) GetAgentsAssetIDStats(params *GetAgentsAssetIDStatsParams, opts ...ClientOption) (*GetAgentsAssetIDStatsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAgentsAssetIDStatsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAgentsAssetIDStats",
		Method:             "GET",
		PathPattern:        "/agents/{asset_id}/stats",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAgentsAssetIDStatsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAgentsAssetIDStatsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAgentsAssetIDStats: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAgentsRuns records agent run
*/
func (a *Client) PostAgentsRuns(params *PostAgentsRunsParams, opts ...ClientOption) (*PostAgentsRunsCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAgentsRunsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAgentsRuns",
		Method:             "POST",
		PathPattern:        "/agents/runs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAgentsRunsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAgentsRunsCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAgentsRuns: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
