// Code generated by go-swagger; DO NOT EDIT.

package agents

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostAgentsRunsReader is a Reader for the PostAgentsRuns structure.
type PostAgentsRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAgentsRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostAgentsRunsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /agents/runs] PostAgentsRuns", response, response.Code())
	}
}

// NewPostAgentsRunsCreated creates a PostAgentsRunsCreated with default headers values
func NewPostAgentsRunsCreated() *PostAgentsRunsCreated {
	return &PostAgentsRunsCreated{}
}

/*
PostAgentsRunsCreated describes a response with status code 201, with default header values.

Created
*/
type PostAgentsRunsCreated struct {
	Payload *models.AgentRun
}

// IsSuccess returns true when this post agents runs created response has a 2xx status code
func (o *PostAgentsRunsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post agents runs created response has a 3xx status code
func (o *PostAgentsRunsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post agents runs created response has a 4xx status code
func (o *PostAgentsRunsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post agents runs created response has a 5xx status code
func (o *PostAgentsRunsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post agents runs created response a status code equal to that given
func (o *PostAgentsRunsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post agents runs created response
func (o *PostAgentsRunsCreated) Code() int {
	return 201
}

func (o *PostAgentsRunsCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /agents/runs][%d] postAgentsRunsCreated %s", 201, payload)
}

func (o *PostAgentsRunsCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /agents/runs][%d] postAgentsRunsCreated %s", 201, payload)
}

func (o *PostAgentsRunsCreated) GetPayload() *models.AgentRun {
	return o.Payload
}

func (o *PostAgentsRunsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AgentRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
