// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new asset rules API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new asset rules API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new asset rules API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for asset rules API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAssetRulesID(params *DeleteAssetRulesIDParams, opts ...ClientOption) (*DeleteAssetRulesIDNoContent, error)

	GetAssetRulesAssetsID(params *GetAssetRulesAssetsIDParams, opts ...ClientOption) (*GetAssetRulesAssetsIDOK, error)

	GetAssetRulesID(params *GetAssetRulesIDParams, opts ...ClientOption) (*GetAssetRulesIDOK, error)

	GetAssetRulesList(params *GetAssetRulesListParams, opts ...ClientOption) (*GetAssetRulesListOK, error)

	GetAssetRulesSearch(params *GetAssetRulesSearchParams, opts ...ClientOption) (*GetAssetRulesSearchOK, error)

	PostAssetRules(params *PostAssetRulesParams, opts ...ClientOption) (*PostAssetRulesCreated, error)

	PostAssetRulesPreview(params *PostAssetRulesPreviewParams, opts ...ClientOption) (*PostAssetRulesPreviewOK, error)

	PutAssetRulesID(params *PutAssetRulesIDParams, opts ...ClientOption) (*PutAssetRulesIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAssetRulesID deletes an asset rule

Delete an asset rule by ID
*/
func (a *Client) DeleteAssetRulesID(params *DeleteAssetRulesIDParams, opts ...ClientOption) (*DeleteAssetRulesIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAssetRulesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAssetRulesID",
		Method:             "DELETE",
		PathPattern:        "/asset-rules/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAssetRulesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAssetRulesIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAssetRulesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAssetRulesAssetsID gets assets matched by a rule

Get the list of asset IDs matched by an asset rule
*/
func (a *Client) GetAssetRulesAssetsID(params *GetAssetRulesAssetsIDParams, opts ...ClientOption) (*GetAssetRulesAssetsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAssetRulesAssetsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAssetRulesAssetsID",
		Method:             "GET",
		PathPattern:        "/asset-rules/assets/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetRulesAssetsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAssetRulesAssetsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAssetRulesAssetsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAssetRulesID gets an asset rule

Get an asset rule by ID
*/
func (a *Client) GetAssetRulesID(params *GetAssetRulesIDParams, opts ...ClientOption) (*GetAssetRulesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAssetRulesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAssetRulesID",
		Method:             "GET",
		PathPattern:        "/asset-rules/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetRulesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAssetRulesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAssetRulesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAssetRulesList lists asset rules

List all asset rules with pagination
*/
func (a *Client) GetAssetRulesList(params *GetAssetRulesListParams, opts ...ClientOption) (*GetAssetRulesListOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAssetRulesListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAssetRulesList",
		Method:             "GET",
		PathPattern:        "/asset-rules/list",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetRulesListReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAssetRulesListOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAssetRulesList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAssetRulesSearch searches asset rules

Search asset rules by name
*/
func (a *Client) GetAssetRulesSearch(params *GetAssetRulesSearchParams, opts ...ClientOption) (*GetAssetRulesSearchOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAssetRulesSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAssetRulesSearch",
		Method:             "GET",
		PathPattern:        "/asset-rules/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetRulesSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAssetRulesSearchOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAssetRulesSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAssetRules creates an asset rule

Create a new asset rule that applies enrichments to matching assets
*/
func (a *Client) PostAssetRules(params *PostAssetRulesParams, opts ...ClientOption) (*PostAssetRulesCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAssetRulesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAssetRules",
		Method:             "POST",
		PathPattern:        "/asset-rules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAssetRulesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAssetRulesCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAssetRules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAssetRulesPreview previews an asset rule

Preview which assets would match a rule configuration
*/
func (a *Client) PostAssetRulesPreview(params *PostAssetRulesPreviewParams, opts ...ClientOption) (*PostAssetRulesPreviewOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAssetRulesPreviewParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAssetRulesPreview",
		Method:             "POST",
		PathPattern:        "/asset-rules/preview",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAssetRulesPreviewReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAssetRulesPreviewOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAssetRulesPreview: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAssetRulesID updates an asset rule

Update an existing asset rule
*/
func (a *Client) PutAssetRulesID(params *PutAssetRulesIDParams, opts ...ClientOption) (*PutAssetRulesIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAssetRulesIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAssetRulesID",
		Method:             "PUT",
		PathPattern:        "/asset-rules/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAssetRulesIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAssetRulesIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAssetRulesID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
