// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// DeleteAssetRulesIDReader is a Reader for the DeleteAssetRulesID structure.
type DeleteAssetRulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAssetRulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAssetRulesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAssetRulesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAssetRulesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /asset-rules/{id}] DeleteAssetRulesID", response, response.Code())
	}
}

// NewDeleteAssetRulesIDNoContent creates a DeleteAssetRulesIDNoContent with default headers values
func NewDeleteAssetRulesIDNoContent() *DeleteAssetRulesIDNoContent {
	return &DeleteAssetRulesIDNoContent{}
}

/*
DeleteAssetRulesIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAssetRulesIDNoContent struct {
}

// IsSuccess returns true when this delete asset rules Id no content response has a 2xx status code
func (o *DeleteAssetRulesIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete asset rules Id no content response has a 3xx status code
func (o *DeleteAssetRulesIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete asset rules Id no content response has a 4xx status code
func (o *DeleteAssetRulesIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete asset rules Id no content response has a 5xx status code
func (o *DeleteAssetRulesIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete asset rules Id no content response a status code equal to that given
func (o *DeleteAssetRulesIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete asset rules Id no content response
func (o *DeleteAssetRulesIDNoContent) Code() int {
	return 204
}

func (o *DeleteAssetRulesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdNoContent", 204)
}

func (o *DeleteAssetRulesIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdNoContent", 204)
}

func (o *DeleteAssetRulesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAssetRulesIDNotFound creates a DeleteAssetRulesIDNotFound with default headers values
func NewDeleteAssetRulesIDNotFound() *DeleteAssetRulesIDNotFound {
	return &DeleteAssetRulesIDNotFound{}
}

/*
DeleteAssetRulesIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAssetRulesIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete asset rules Id not found response has a 2xx status code
func (o *DeleteAssetRulesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete asset rules Id not found response has a 3xx status code
func (o *DeleteAssetRulesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete asset rules Id not found response has a 4xx status code
func (o *DeleteAssetRulesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete asset rules Id not found response has a 5xx status code
func (o *DeleteAssetRulesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete asset rules Id not found response a status code equal to that given
func (o *DeleteAssetRulesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete asset rules Id not found response
func (o *DeleteAssetRulesIDNotFound) Code() int {
	return 404
}

func (o *DeleteAssetRulesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdNotFound %s", 404, payload)
}

func (o *DeleteAssetRulesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdNotFound %s", 404, payload)
}

func (o *DeleteAssetRulesIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteAssetRulesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAssetRulesIDInternalServerError creates a DeleteAssetRulesIDInternalServerError with default headers values
func NewDeleteAssetRulesIDInternalServerError() *DeleteAssetRulesIDInternalServerError {
	return &DeleteAssetRulesIDInternalServerError{}
}

/*
DeleteAssetRulesIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteAssetRulesIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete asset rules Id internal server error response has a 2xx status code
func (o *DeleteAssetRulesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete asset rules Id internal server error response has a 3xx status code
func (o *DeleteAssetRulesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete asset rules Id internal server error response has a 4xx status code
func (o *DeleteAssetRulesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete asset rules Id internal server error response has a 5xx status code
func (o *DeleteAssetRulesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete asset rules Id internal server error response a status code equal to that given
func (o *DeleteAssetRulesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete asset rules Id internal server error response
func (o *DeleteAssetRulesIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAssetRulesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *DeleteAssetRulesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /asset-rules/{id}][%d] deleteAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *DeleteAssetRulesIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteAssetRulesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
