// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAssetRulesIDParams creates a new GetAssetRulesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetRulesIDParams() *GetAssetRulesIDParams {
	return &GetAssetRulesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetRulesIDParamsWithTimeout creates a new GetAssetRulesIDParams object
// with the ability to set a timeout on a request.
func NewGetAssetRulesIDParamsWithTimeout(timeout time.Duration) *GetAssetRulesIDParams {
	return &GetAssetRulesIDParams{
		timeout: timeout,
	}
}

// NewGetAssetRulesIDParamsWithContext creates a new GetAssetRulesIDParams object
// with the ability to set a context for a request.
func NewGetAssetRulesIDParamsWithContext(ctx context.Context) *GetAssetRulesIDParams {
	return &GetAssetRulesIDParams{
		Context: ctx,
	}
}

// NewGetAssetRulesIDParamsWithHTTPClient creates a new GetAssetRulesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetRulesIDParamsWithHTTPClient(client *http.Client) *GetAssetRulesIDParams {
	return &GetAssetRulesIDParams{
		HTTPClient: client,
	}
}

/*
GetAssetRulesIDParams contains all the parameters to send to the API endpoint

	for the get asset rules ID operation.

	Typically these are written to a http.Request.
*/
type GetAssetRulesIDParams struct {

	/* ID.

	   Asset rule ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get asset rules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesIDParams) WithDefaults() *GetAssetRulesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get asset rules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get asset rules ID params
func (o *GetAssetRulesIDParams) WithTimeout(timeout time.Duration) *GetAssetRulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get asset rules ID params
func (o *GetAssetRulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get asset rules ID params
func (o *GetAssetRulesIDParams) WithContext(ctx context.Context) *GetAssetRulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get asset rules ID params
func (o *GetAssetRulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get asset rules ID params
func (o *GetAssetRulesIDParams) WithHTTPClient(client *http.Client) *GetAssetRulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get asset rules ID params
func (o *GetAssetRulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get asset rules ID params
func (o *GetAssetRulesIDParams) WithID(id string) *GetAssetRulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get asset rules ID params
func (o *GetAssetRulesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetRulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
