// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetAssetRulesIDReader is a Reader for the GetAssetRulesID structure.
type GetAssetRulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetRulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetRulesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAssetRulesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAssetRulesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /asset-rules/{id}] GetAssetRulesID", response, response.Code())
	}
}

// NewGetAssetRulesIDOK creates a GetAssetRulesIDOK with default headers values
func NewGetAssetRulesIDOK() *GetAssetRulesIDOK {
	return &GetAssetRulesIDOK{}
}

/*
GetAssetRulesIDOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetRulesIDOK struct {
	Payload *models.AssetruleAssetRule
}

// IsSuccess returns true when this get asset rules Id o k response has a 2xx status code
func (o *GetAssetRulesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get asset rules Id o k response has a 3xx status code
func (o *GetAssetRulesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get asset rules Id o k response has a 4xx status code
func (o *GetAssetRulesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get asset rules Id o k response has a 5xx status code
func (o *GetAssetRulesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get asset rules Id o k response a status code equal to that given
func (o *GetAssetRulesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get asset rules Id o k response
func (o *GetAssetRulesIDOK) Code() int {
	return 200
}

func (o *GetAssetRulesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdOK %s", 200, payload)
}

func (o *GetAssetRulesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdOK %s", 200, payload)
}

func (o *GetAssetRulesIDOK) GetPayload() *models.AssetruleAssetRule {
	return o.Payload
}

func (o *GetAssetRulesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetruleAssetRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAssetRulesIDNotFound creates a GetAssetRulesIDNotFound with default headers values
func NewGetAssetRulesIDNotFound() *GetAssetRulesIDNotFound {
	return &GetAssetRulesIDNotFound{}
}

/*
GetAssetRulesIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAssetRulesIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get asset rules Id not found response has a 2xx status code
func (o *GetAssetRulesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get asset rules Id not found response has a 3xx status code
func (o *GetAssetRulesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get asset rules Id not found response has a 4xx status code
func (o *GetAssetRulesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get asset rules Id not found response has a 5xx status code
func (o *GetAssetRulesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get asset rules Id not found response a status code equal to that given
func (o *GetAssetRulesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get asset rules Id not found response
func (o *GetAssetRulesIDNotFound) Code() int {
	return 404
}

func (o *GetAssetRulesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdNotFound %s", 404, payload)
}

func (o *GetAssetRulesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdNotFound %s", 404, payload)
}

func (o *GetAssetRulesIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetRulesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAssetRulesIDInternalServerError creates a GetAssetRulesIDInternalServerError with default headers values
func NewGetAssetRulesIDInternalServerError() *GetAssetRulesIDInternalServerError {
	return &GetAssetRulesIDInternalServerError{}
}

/*
GetAssetRulesIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetRulesIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get asset rules Id internal server error response has a 2xx status code
func (o *GetAssetRulesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get asset rules Id internal server error response has a 3xx status code
func (o *GetAssetRulesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get asset rules Id internal server error response has a 4xx status code
func (o *GetAssetRulesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get asset rules Id internal server error response has a 5xx status code
func (o *GetAssetRulesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get asset rules Id internal server error response a status code equal to that given
func (o *GetAssetRulesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get asset rules Id internal server error response
func (o *GetAssetRulesIDInternalServerError) Code() int {
	return 500
}

func (o *GetAssetRulesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *GetAssetRulesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/{id}][%d] getAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *GetAssetRulesIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetRulesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
