// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetAssetRulesSearchReader is a Reader for the GetAssetRulesSearch structure.
type GetAssetRulesSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAssetRulesSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAssetRulesSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAssetRulesSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /asset-rules/search] GetAssetRulesSearch", response, response.Code())
	}
}

// NewGetAssetRulesSearchOK creates a GetAssetRulesSearchOK with default headers values
func NewGetAssetRulesSearchOK() *GetAssetRulesSearchOK {
	return &GetAssetRulesSearchOK{}
}

/*
GetAssetRulesSearchOK describes a response with status code 200, with default header values.

OK
*/
type GetAssetRulesSearchOK struct {
	Payload *models.AssetruleListResult
}

// IsSuccess returns true when this get asset rules search o k response has a 2xx status code
func (o *GetAssetRulesSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get asset rules search o k response has a 3xx status code
func (o *GetAssetRulesSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get asset rules search o k response has a 4xx status code
func (o *GetAssetRulesSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get asset rules search o k response has a 5xx status code
func (o *GetAssetRulesSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get asset rules search o k response a status code equal to that given
func (o *GetAssetRulesSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get asset rules search o k response
func (o *GetAssetRulesSearchOK) Code() int {
	return 200
}

func (o *GetAssetRulesSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/search][%d] getAssetRulesSearchOK %s", 200, payload)
}

func (o *GetAssetRulesSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/search][%d] getAssetRulesSearchOK %s", 200, payload)
}

func (o *GetAssetRulesSearchOK) GetPayload() *models.AssetruleListResult {
	return o.Payload
}

func (o *GetAssetRulesSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetruleListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAssetRulesSearchInternalServerError creates a GetAssetRulesSearchInternalServerError with default headers values
func NewGetAssetRulesSearchInternalServerError() *GetAssetRulesSearchInternalServerError {
	return &GetAssetRulesSearchInternalServerError{}
}

/*
GetAssetRulesSearchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAssetRulesSearchInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get asset rules search internal server error response has a 2xx status code
func (o *GetAssetRulesSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get asset rules search internal server error response has a 3xx status code
func (o *GetAssetRulesSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get asset rules search internal server error response has a 4xx status code
func (o *GetAssetRulesSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get asset rules search internal server error response has a 5xx status code
func (o *GetAssetRulesSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get asset rules search internal server error response a status code equal to that given
func (o *GetAssetRulesSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get asset rules search internal server error response
func (o *GetAssetRulesSearchInternalServerError) Code() int {
	return 500
}

func (o *GetAssetRulesSearchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/search][%d] getAssetRulesSearchInternalServerError %s", 500, payload)
}

func (o *GetAssetRulesSearchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /asset-rules/search][%d] getAssetRulesSearchInternalServerError %s", 500, payload)
}

func (o *GetAssetRulesSearchInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAssetRulesSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
