// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetRulesAssetsIDParams creates a new GetAssetRulesAssetsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetRulesAssetsIDParams() *GetAssetRulesAssetsIDParams {
	return &GetAssetRulesAssetsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetRulesAssetsIDParamsWithTimeout creates a new GetAssetRulesAssetsIDParams object
// with the ability to set a timeout on a request.
func NewGetAssetRulesAssetsIDParamsWithTimeout(timeout time.Duration) *GetAssetRulesAssetsIDParams {
	return &GetAssetRulesAssetsIDParams{
		timeout: timeout,
	}
}

// NewGetAssetRulesAssetsIDParamsWithContext creates a new GetAssetRulesAssetsIDParams object
// with the ability to set a context for a request.
func NewGetAssetRulesAssetsIDParamsWithContext(ctx context.Context) *GetAssetRulesAssetsIDParams {
	return &GetAssetRulesAssetsIDParams{
		Context: ctx,
	}
}

// NewGetAssetRulesAssetsIDParamsWithHTTPClient creates a new GetAssetRulesAssetsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetRulesAssetsIDParamsWithHTTPClient(client *http.Client) *GetAssetRulesAssetsIDParams {
	return &GetAssetRulesAssetsIDParams{
		HTTPClient: client,
	}
}

/*
GetAssetRulesAssetsIDParams contains all the parameters to send to the API endpoint

	for the get asset rules assets ID operation.

	Typically these are written to a http.Request.
*/
type GetAssetRulesAssetsIDParams struct {

	/* ID.

	   Asset rule ID
	*/
	ID string

	/* Limit.

	   Number of items to return

	   Default: 50
	*/
	Limit *int64

	/* Offset.

	   Number of items to skip
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get asset rules assets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesAssetsIDParams) WithDefaults() *GetAssetRulesAssetsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get asset rules assets ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesAssetsIDParams) SetDefaults() {
	var (
		limitDefault = int64(50)

		offsetDefault = int64(0)
	)

	val := GetAssetRulesAssetsIDParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithTimeout(timeout time.Duration) *GetAssetRulesAssetsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithContext(ctx context.Context) *GetAssetRulesAssetsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithHTTPClient(client *http.Client) *GetAssetRulesAssetsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithID(id string) *GetAssetRulesAssetsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithLimit(limit *int64) *GetAssetRulesAssetsIDParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) WithOffset(offset *int64) *GetAssetRulesAssetsIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get asset rules assets ID params
func (o *GetAssetRulesAssetsIDParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetRulesAssetsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
