// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAssetRulesSearchParams creates a new GetAssetRulesSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAssetRulesSearchParams() *GetAssetRulesSearchParams {
	return &GetAssetRulesSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAssetRulesSearchParamsWithTimeout creates a new GetAssetRulesSearchParams object
// with the ability to set a timeout on a request.
func NewGetAssetRulesSearchParamsWithTimeout(timeout time.Duration) *GetAssetRulesSearchParams {
	return &GetAssetRulesSearchParams{
		timeout: timeout,
	}
}

// NewGetAssetRulesSearchParamsWithContext creates a new GetAssetRulesSearchParams object
// with the ability to set a context for a request.
func NewGetAssetRulesSearchParamsWithContext(ctx context.Context) *GetAssetRulesSearchParams {
	return &GetAssetRulesSearchParams{
		Context: ctx,
	}
}

// NewGetAssetRulesSearchParamsWithHTTPClient creates a new GetAssetRulesSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAssetRulesSearchParamsWithHTTPClient(client *http.Client) *GetAssetRulesSearchParams {
	return &GetAssetRulesSearchParams{
		HTTPClient: client,
	}
}

/*
GetAssetRulesSearchParams contains all the parameters to send to the API endpoint

	for the get asset rules search operation.

	Typically these are written to a http.Request.
*/
type GetAssetRulesSearchParams struct {

	/* Limit.

	   Number of items to return

	   Default: 50
	*/
	Limit *int64

	/* Offset.

	   Number of items to skip
	*/
	Offset *int64

	/* Query.

	   Search query
	*/
	Query *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get asset rules search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesSearchParams) WithDefaults() *GetAssetRulesSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get asset rules search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAssetRulesSearchParams) SetDefaults() {
	var (
		limitDefault = int64(50)

		offsetDefault = int64(0)
	)

	val := GetAssetRulesSearchParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithTimeout(timeout time.Duration) *GetAssetRulesSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithContext(ctx context.Context) *GetAssetRulesSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithHTTPClient(client *http.Client) *GetAssetRulesSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithLimit(limit *int64) *GetAssetRulesSearchParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithOffset(offset *int64) *GetAssetRulesSearchParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQuery adds the query to the get asset rules search params
func (o *GetAssetRulesSearchParams) WithQuery(query *string) *GetAssetRulesSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get asset rules search params
func (o *GetAssetRulesSearchParams) SetQuery(query *string) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *GetAssetRulesSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Query != nil {

		// query param query
		var qrQuery string

		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {

			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
