// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostAssetRulesPreviewReader is a Reader for the PostAssetRulesPreview structure.
type PostAssetRulesPreviewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAssetRulesPreviewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAssetRulesPreviewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAssetRulesPreviewBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAssetRulesPreviewInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /asset-rules/preview] PostAssetRulesPreview", response, response.Code())
	}
}

// NewPostAssetRulesPreviewOK creates a PostAssetRulesPreviewOK with default headers values
func NewPostAssetRulesPreviewOK() *PostAssetRulesPreviewOK {
	return &PostAssetRulesPreviewOK{}
}

/*
PostAssetRulesPreviewOK describes a response with status code 200, with default header values.

OK
*/
type PostAssetRulesPreviewOK struct {
	Payload *models.AssetruleRulePreview
}

// IsSuccess returns true when this post asset rules preview o k response has a 2xx status code
func (o *PostAssetRulesPreviewOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post asset rules preview o k response has a 3xx status code
func (o *PostAssetRulesPreviewOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post asset rules preview o k response has a 4xx status code
func (o *PostAssetRulesPreviewOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post asset rules preview o k response has a 5xx status code
func (o *PostAssetRulesPreviewOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post asset rules preview o k response a status code equal to that given
func (o *PostAssetRulesPreviewOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post asset rules preview o k response
func (o *PostAssetRulesPreviewOK) Code() int {
	return 200
}

func (o *PostAssetRulesPreviewOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewOK %s", 200, payload)
}

func (o *PostAssetRulesPreviewOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewOK %s", 200, payload)
}

func (o *PostAssetRulesPreviewOK) GetPayload() *models.AssetruleRulePreview {
	return o.Payload
}

func (o *PostAssetRulesPreviewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetruleRulePreview)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAssetRulesPreviewBadRequest creates a PostAssetRulesPreviewBadRequest with default headers values
func NewPostAssetRulesPreviewBadRequest() *PostAssetRulesPreviewBadRequest {
	return &PostAssetRulesPreviewBadRequest{}
}

/*
PostAssetRulesPreviewBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAssetRulesPreviewBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post asset rules preview bad request response has a 2xx status code
func (o *PostAssetRulesPreviewBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post asset rules preview bad request response has a 3xx status code
func (o *PostAssetRulesPreviewBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post asset rules preview bad request response has a 4xx status code
func (o *PostAssetRulesPreviewBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post asset rules preview bad request response has a 5xx status code
func (o *PostAssetRulesPreviewBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post asset rules preview bad request response a status code equal to that given
func (o *PostAssetRulesPreviewBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post asset rules preview bad request response
func (o *PostAssetRulesPreviewBadRequest) Code() int {
	return 400
}

func (o *PostAssetRulesPreviewBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewBadRequest %s", 400, payload)
}

func (o *PostAssetRulesPreviewBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewBadRequest %s", 400, payload)
}

func (o *PostAssetRulesPreviewBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAssetRulesPreviewBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAssetRulesPreviewInternalServerError creates a PostAssetRulesPreviewInternalServerError with default headers values
func NewPostAssetRulesPreviewInternalServerError() *PostAssetRulesPreviewInternalServerError {
	return &PostAssetRulesPreviewInternalServerError{}
}

/*
PostAssetRulesPreviewInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAssetRulesPreviewInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post asset rules preview internal server error response has a 2xx status code
func (o *PostAssetRulesPreviewInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post asset rules preview internal server error response has a 3xx status code
func (o *PostAssetRulesPreviewInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post asset rules preview internal server error response has a 4xx status code
func (o *PostAssetRulesPreviewInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post asset rules preview internal server error response has a 5xx status code
func (o *PostAssetRulesPreviewInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post asset rules preview internal server error response a status code equal to that given
func (o *PostAssetRulesPreviewInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post asset rules preview internal server error response
func (o *PostAssetRulesPreviewInternalServerError) Code() int {
	return 500
}

func (o *PostAssetRulesPreviewInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewInternalServerError %s", 500, payload)
}

func (o *PostAssetRulesPreviewInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /asset-rules/preview][%d] postAssetRulesPreviewInternalServerError %s", 500, payload)
}

func (o *PostAssetRulesPreviewInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostAssetRulesPreviewInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
