// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// NewPostAssetRulesPreviewParams creates a new PostAssetRulesPreviewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAssetRulesPreviewParams() *PostAssetRulesPreviewParams {
	return &PostAssetRulesPreviewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAssetRulesPreviewParamsWithTimeout creates a new PostAssetRulesPreviewParams object
// with the ability to set a timeout on a request.
func NewPostAssetRulesPreviewParamsWithTimeout(timeout time.Duration) *PostAssetRulesPreviewParams {
	return &PostAssetRulesPreviewParams{
		timeout: timeout,
	}
}

// NewPostAssetRulesPreviewParamsWithContext creates a new PostAssetRulesPreviewParams object
// with the ability to set a context for a request.
func NewPostAssetRulesPreviewParamsWithContext(ctx context.Context) *PostAssetRulesPreviewParams {
	return &PostAssetRulesPreviewParams{
		Context: ctx,
	}
}

// NewPostAssetRulesPreviewParamsWithHTTPClient creates a new PostAssetRulesPreviewParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAssetRulesPreviewParamsWithHTTPClient(client *http.Client) *PostAssetRulesPreviewParams {
	return &PostAssetRulesPreviewParams{
		HTTPClient: client,
	}
}

/*
PostAssetRulesPreviewParams contains all the parameters to send to the API endpoint

	for the post asset rules preview operation.

	Typically these are written to a http.Request.
*/
type PostAssetRulesPreviewParams struct {

	/* Rule.

	   Rule preview request
	*/
	Rule *models.V1AssetrulesPreviewRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post asset rules preview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAssetRulesPreviewParams) WithDefaults() *PostAssetRulesPreviewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post asset rules preview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAssetRulesPreviewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) WithTimeout(timeout time.Duration) *PostAssetRulesPreviewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) WithContext(ctx context.Context) *PostAssetRulesPreviewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) WithHTTPClient(client *http.Client) *PostAssetRulesPreviewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRule adds the rule to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) WithRule(rule *models.V1AssetrulesPreviewRequest) *PostAssetRulesPreviewParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the post asset rules preview params
func (o *PostAssetRulesPreviewParams) SetRule(rule *models.V1AssetrulesPreviewRequest) {
	o.Rule = rule
}

// WriteToRequest writes these params to a swagger request
func (o *PostAssetRulesPreviewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Rule != nil {
		if err := r.SetBodyParam(o.Rule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
