// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PutAssetRulesIDReader is a Reader for the PutAssetRulesID structure.
type PutAssetRulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAssetRulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAssetRulesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAssetRulesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAssetRulesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutAssetRulesIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAssetRulesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /asset-rules/{id}] PutAssetRulesID", response, response.Code())
	}
}

// NewPutAssetRulesIDOK creates a PutAssetRulesIDOK with default headers values
func NewPutAssetRulesIDOK() *PutAssetRulesIDOK {
	return &PutAssetRulesIDOK{}
}

/*
PutAssetRulesIDOK describes a response with status code 200, with default header values.

OK
*/
type PutAssetRulesIDOK struct {
	Payload *models.AssetruleAssetRule
}

// IsSuccess returns true when this put asset rules Id o k response has a 2xx status code
func (o *PutAssetRulesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put asset rules Id o k response has a 3xx status code
func (o *PutAssetRulesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put asset rules Id o k response has a 4xx status code
func (o *PutAssetRulesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put asset rules Id o k response has a 5xx status code
func (o *PutAssetRulesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put asset rules Id o k response a status code equal to that given
func (o *PutAssetRulesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put asset rules Id o k response
func (o *PutAssetRulesIDOK) Code() int {
	return 200
}

func (o *PutAssetRulesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdOK %s", 200, payload)
}

func (o *PutAssetRulesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdOK %s", 200, payload)
}

func (o *PutAssetRulesIDOK) GetPayload() *models.AssetruleAssetRule {
	return o.Payload
}

func (o *PutAssetRulesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssetruleAssetRule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAssetRulesIDBadRequest creates a PutAssetRulesIDBadRequest with default headers values
func NewPutAssetRulesIDBadRequest() *PutAssetRulesIDBadRequest {
	return &PutAssetRulesIDBadRequest{}
}

/*
PutAssetRulesIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAssetRulesIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put asset rules Id bad request response has a 2xx status code
func (o *PutAssetRulesIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put asset rules Id bad request response has a 3xx status code
func (o *PutAssetRulesIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put asset rules Id bad request response has a 4xx status code
func (o *PutAssetRulesIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put asset rules Id bad request response has a 5xx status code
func (o *PutAssetRulesIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put asset rules Id bad request response a status code equal to that given
func (o *PutAssetRulesIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put asset rules Id bad request response
func (o *PutAssetRulesIDBadRequest) Code() int {
	return 400
}

func (o *PutAssetRulesIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdBadRequest %s", 400, payload)
}

func (o *PutAssetRulesIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdBadRequest %s", 400, payload)
}

func (o *PutAssetRulesIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetRulesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAssetRulesIDNotFound creates a PutAssetRulesIDNotFound with default headers values
func NewPutAssetRulesIDNotFound() *PutAssetRulesIDNotFound {
	return &PutAssetRulesIDNotFound{}
}

/*
PutAssetRulesIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAssetRulesIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put asset rules Id not found response has a 2xx status code
func (o *PutAssetRulesIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put asset rules Id not found response has a 3xx status code
func (o *PutAssetRulesIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put asset rules Id not found response has a 4xx status code
func (o *PutAssetRulesIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put asset rules Id not found response has a 5xx status code
func (o *PutAssetRulesIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put asset rules Id not found response a status code equal to that given
func (o *PutAssetRulesIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put asset rules Id not found response
func (o *PutAssetRulesIDNotFound) Code() int {
	return 404
}

func (o *PutAssetRulesIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdNotFound %s", 404, payload)
}

func (o *PutAssetRulesIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdNotFound %s", 404, payload)
}

func (o *PutAssetRulesIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetRulesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAssetRulesIDConflict creates a PutAssetRulesIDConflict with default headers values
func NewPutAssetRulesIDConflict() *PutAssetRulesIDConflict {
	return &PutAssetRulesIDConflict{}
}

/*
PutAssetRulesIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutAssetRulesIDConflict struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put asset rules Id conflict response has a 2xx status code
func (o *PutAssetRulesIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put asset rules Id conflict response has a 3xx status code
func (o *PutAssetRulesIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put asset rules Id conflict response has a 4xx status code
func (o *PutAssetRulesIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put asset rules Id conflict response has a 5xx status code
func (o *PutAssetRulesIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put asset rules Id conflict response a status code equal to that given
func (o *PutAssetRulesIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put asset rules Id conflict response
func (o *PutAssetRulesIDConflict) Code() int {
	return 409
}

func (o *PutAssetRulesIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdConflict %s", 409, payload)
}

func (o *PutAssetRulesIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdConflict %s", 409, payload)
}

func (o *PutAssetRulesIDConflict) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetRulesIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAssetRulesIDInternalServerError creates a PutAssetRulesIDInternalServerError with default headers values
func NewPutAssetRulesIDInternalServerError() *PutAssetRulesIDInternalServerError {
	return &PutAssetRulesIDInternalServerError{}
}

/*
PutAssetRulesIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutAssetRulesIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put asset rules Id internal server error response has a 2xx status code
func (o *PutAssetRulesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put asset rules Id internal server error response has a 3xx status code
func (o *PutAssetRulesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put asset rules Id internal server error response has a 4xx status code
func (o *PutAssetRulesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put asset rules Id internal server error response has a 5xx status code
func (o *PutAssetRulesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put asset rules Id internal server error response a status code equal to that given
func (o *PutAssetRulesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put asset rules Id internal server error response
func (o *PutAssetRulesIDInternalServerError) Code() int {
	return 500
}

func (o *PutAssetRulesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *PutAssetRulesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /asset-rules/{id}][%d] putAssetRulesIdInternalServerError %s", 500, payload)
}

func (o *PutAssetRulesIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutAssetRulesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
