// Code generated by go-swagger; DO NOT EDIT.

package asset_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// NewPutAssetRulesIDParams creates a new PutAssetRulesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAssetRulesIDParams() *PutAssetRulesIDParams {
	return &PutAssetRulesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAssetRulesIDParamsWithTimeout creates a new PutAssetRulesIDParams object
// with the ability to set a timeout on a request.
func NewPutAssetRulesIDParamsWithTimeout(timeout time.Duration) *PutAssetRulesIDParams {
	return &PutAssetRulesIDParams{
		timeout: timeout,
	}
}

// NewPutAssetRulesIDParamsWithContext creates a new PutAssetRulesIDParams object
// with the ability to set a context for a request.
func NewPutAssetRulesIDParamsWithContext(ctx context.Context) *PutAssetRulesIDParams {
	return &PutAssetRulesIDParams{
		Context: ctx,
	}
}

// NewPutAssetRulesIDParamsWithHTTPClient creates a new PutAssetRulesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAssetRulesIDParamsWithHTTPClient(client *http.Client) *PutAssetRulesIDParams {
	return &PutAssetRulesIDParams{
		HTTPClient: client,
	}
}

/*
PutAssetRulesIDParams contains all the parameters to send to the API endpoint

	for the put asset rules ID operation.

	Typically these are written to a http.Request.
*/
type PutAssetRulesIDParams struct {

	/* ID.

	   Asset rule ID
	*/
	ID string

	/* Rule.

	   Asset rule update request
	*/
	Rule *models.V1AssetrulesUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put asset rules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAssetRulesIDParams) WithDefaults() *PutAssetRulesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put asset rules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAssetRulesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put asset rules ID params
func (o *PutAssetRulesIDParams) WithTimeout(timeout time.Duration) *PutAssetRulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put asset rules ID params
func (o *PutAssetRulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put asset rules ID params
func (o *PutAssetRulesIDParams) WithContext(ctx context.Context) *PutAssetRulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put asset rules ID params
func (o *PutAssetRulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put asset rules ID params
func (o *PutAssetRulesIDParams) WithHTTPClient(client *http.Client) *PutAssetRulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put asset rules ID params
func (o *PutAssetRulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put asset rules ID params
func (o *PutAssetRulesIDParams) WithID(id string) *PutAssetRulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put asset rules ID params
func (o *PutAssetRulesIDParams) SetID(id string) {
	o.ID = id
}

// WithRule adds the rule to the put asset rules ID params
func (o *PutAssetRulesIDParams) WithRule(rule *models.V1AssetrulesUpdateRequest) *PutAssetRulesIDParams {
	o.SetRule(rule)
	return o
}

// SetRule adds the rule to the put asset rules ID params
func (o *PutAssetRulesIDParams) SetRule(rule *models.V1AssetrulesUpdateRequest) {
	o.Rule = rule
}

// WriteToRequest writes these params to a swagger request
func (o *PutAssetRulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Rule != nil {
		if err := r.SetBodyParam(o.Rule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
