FROM gcr.io/distroless/static-debian12:nonroot
LABEL io.modelcontextprotocol.server.name="io.github.marmotdata/marmot"
COPY marmot /usr/local/bin/marmot
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/marmot"]
CMD ["run"]
