#!/usr/bin/env node
/**
 * Emit src/_models.ts from src/_gen/schema.ts.
 *
 * `openapi-typescript` exposes schemas as `components["schemas"]["Foo"]` —
 * awkward to consume directly. This script re-exports each component schema
 * as a flat named type so callers can write `Asset`, `LineageEdge`, etc.
 *
 * Run via `pnpm generate` (chained after openapi-typescript).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const schemaPath = join(root, "src/_gen/schema.ts");
const outPath = join(root, "src/_models.ts");

const lines = readFileSync(schemaPath, "utf8").split("\n");

const names = [];
let inSchemas = false;
for (const line of lines) {
  if (!inSchemas) {
    if (line === "    schemas: {") inSchemas = true;
    continue;
  }
  if (line === "    };") break;
  const m = line.match(/^ {8}([A-Z][A-Za-z0-9_]*):/);
  if (m) names.push(m[1]);
}

if (names.length === 0) {
  console.error(`No component schemas found in ${schemaPath}`);
  process.exit(1);
}

const body = names.map((n) => `export type ${n} = S["${n}"];`).join("\n");

const out = `/**
 * Flat type aliases for every component schema in _gen/schema.ts.
 *
 * Auto-generated by scripts/generate-models.mjs — DO NOT EDIT BY HAND.
 * Regenerate via \`pnpm generate\` after the OpenAPI schema changes.
 */

import type { components } from "./_gen/schema.js";

type S = components["schemas"];

${body}
`;

writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${names.length} types).`);
