// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthTokenExchangeResponse auth token exchange response
//
// swagger:model auth.tokenExchangeResponse
type AuthTokenExchangeResponse struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// issued token type
	IssuedTokenType string `json:"issued_token_type,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this auth token exchange response
func (m *AuthTokenExchangeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth token exchange response based on context it is used
func (m *AuthTokenExchangeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthTokenExchangeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthTokenExchangeResponse) UnmarshalBinary(b []byte) error {
	var res AuthTokenExchangeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
