// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataproductProductImageMeta dataproduct product image meta
//
// swagger:model dataproduct.ProductImageMeta
type DataproductProductImageMeta struct {

	// content type
	ContentType string `json:"content_type,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// data product id
	DataProductID string `json:"data_product_id,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// purpose
	Purpose DataproductImagePurpose `json:"purpose,omitempty"`

	// size bytes
	SizeBytes int64 `json:"size_bytes,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this dataproduct product image meta
func (m *DataproductProductImageMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePurpose(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataproductProductImageMeta) validatePurpose(formats strfmt.Registry) error {
	if swag.IsZero(m.Purpose) { // not required
		return nil
	}

	if err := m.Purpose.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("purpose")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("purpose")
		}

		return err
	}

	return nil
}

// ContextValidate validate this dataproduct product image meta based on the context it is used
func (m *DataproductProductImageMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePurpose(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataproductProductImageMeta) contextValidatePurpose(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Purpose) { // not required
		return nil
	}

	if err := m.Purpose.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("purpose")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("purpose")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataproductProductImageMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataproductProductImageMeta) UnmarshalBinary(b []byte) error {
	var res DataproductProductImageMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
