// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComMarmotdataMarmotInternalCoreSearchResponse github com marmotdata marmot internal core search response
//
// swagger:model github_com_marmotdata_marmot_internal_core_search.Response
type GithubComMarmotdataMarmotInternalCoreSearchResponse struct {

	// facets
	Facets *SearchFacets `json:"facets,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// results
	Results []*SearchResult `json:"results"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this github com marmotdata marmot internal core search response
func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFacets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) validateFacets(formats strfmt.Registry) error {
	if swag.IsZero(m.Facets) { // not required
		return nil
	}

	if m.Facets != nil {
		if err := m.Facets.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("facets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("facets")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) validateResults(formats strfmt.Registry) error {
	if swag.IsZero(m.Results) { // not required
		return nil
	}

	for i := 0; i < len(m.Results); i++ {
		if swag.IsZero(m.Results[i]) { // not required
			continue
		}

		if m.Results[i] != nil {
			if err := m.Results[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("results" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("results" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this github com marmotdata marmot internal core search response based on the context it is used
func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFacets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) contextValidateFacets(ctx context.Context, formats strfmt.Registry) error {

	if m.Facets != nil {

		if swag.IsZero(m.Facets) { // not required
			return nil
		}

		if err := m.Facets.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("facets")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("facets")
			}

			return err
		}
	}

	return nil
}

func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Results); i++ {

		if m.Results[i] != nil {

			if swag.IsZero(m.Results[i]) { // not required
				return nil
			}

			if err := m.Results[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("results" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("results" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComMarmotdataMarmotInternalCoreSearchResponse) UnmarshalBinary(b []byte) error {
	var res GithubComMarmotdataMarmotInternalCoreSearchResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
