// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TeamTeamMemberWithUser team team member with user
//
// swagger:model team.TeamMemberWithUser
type TeamTeamMemberWithUser struct {

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// joined at
	JoinedAt string `json:"joined_at,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// profile picture
	ProfilePicture string `json:"profile_picture,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// sso provider
	SsoProvider string `json:"sso_provider,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this team team member with user
func (m *TeamTeamMemberWithUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this team team member with user based on context it is used
func (m *TeamTeamMemberWithUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TeamTeamMemberWithUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamTeamMemberWithUser) UnmarshalBinary(b []byte) error {
	var res TeamTeamMemberWithUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
