// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AdminReindexStatusResponse v1 admin reindex status response
//
// swagger:model v1_admin.ReindexStatusResponse
type V1AdminReindexStatusResponse struct {

	// es configured
	EsConfigured bool `json:"es_configured,omitempty"`

	// running
	Running bool `json:"running,omitempty"`
}

// Validate validates this v1 admin reindex status response
func (m *V1AdminReindexStatusResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 admin reindex status response based on context it is used
func (m *V1AdminReindexStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AdminReindexStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AdminReindexStatusResponse) UnmarshalBinary(b []byte) error {
	var res V1AdminReindexStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
