// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AssetrulesPreviewRequest v1 assetrules preview request
//
// swagger:model v1_assetrules.PreviewRequest
type V1AssetrulesPreviewRequest struct {

	// limit
	Limit int64 `json:"limit,omitempty"`

	// metadata field
	MetadataField string `json:"metadata_field,omitempty"`

	// pattern type
	PatternType string `json:"pattern_type,omitempty"`

	// pattern value
	PatternValue string `json:"pattern_value,omitempty"`

	// query expression
	QueryExpression string `json:"query_expression,omitempty"`

	// rule type
	RuleType string `json:"rule_type,omitempty"`
}

// Validate validates this v1 assetrules preview request
func (m *V1AssetrulesPreviewRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 assetrules preview request based on context it is used
func (m *V1AssetrulesPreviewRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AssetrulesPreviewRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AssetrulesPreviewRequest) UnmarshalBinary(b []byte) error {
	var res V1AssetrulesPreviewRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
