// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AssetsPreviewResponse v1 assets preview response
//
// swagger:model v1_assets.PreviewResponse
type V1AssetsPreviewResponse struct {

	// column names
	ColumnNames []string `json:"column_names"`

	// rows
	Rows [][]any `json:"rows"`

	// total rows
	TotalRows int64 `json:"total_rows,omitempty"`
}

// Validate validates this v1 assets preview response
func (m *V1AssetsPreviewResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 assets preview response based on context it is used
func (m *V1AssetsPreviewResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AssetsPreviewResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AssetsPreviewResponse) UnmarshalBinary(b []byte) error {
	var res V1AssetsPreviewResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
