// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AssetrulesUpdateRequest v1 assetrules update request
//
// swagger:model v1_assetrules.UpdateRequest
type V1AssetrulesUpdateRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// is enabled
	IsEnabled bool `json:"is_enabled,omitempty"`

	// links
	Links []*AssetruleExternalLink `json:"links"`

	// metadata field
	MetadataField string `json:"metadata_field,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pattern type
	PatternType string `json:"pattern_type,omitempty"`

	// pattern value
	PatternValue string `json:"pattern_value,omitempty"`

	// priority
	Priority int64 `json:"priority,omitempty"`

	// query expression
	QueryExpression string `json:"query_expression,omitempty"`

	// rule type
	RuleType string `json:"rule_type,omitempty"`

	// term ids
	TermIds []string `json:"term_ids"`
}

// Validate validates this v1 assetrules update request
func (m *V1AssetrulesUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AssetrulesUpdateRequest) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	for i := 0; i < len(m.Links); i++ {
		if swag.IsZero(m.Links[i]) { // not required
			continue
		}

		if m.Links[i] != nil {
			if err := m.Links[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("links" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("links" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 assetrules update request based on the context it is used
func (m *V1AssetrulesUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AssetrulesUpdateRequest) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Links); i++ {

		if m.Links[i] != nil {

			if swag.IsZero(m.Links[i]) { // not required
				return nil
			}

			if err := m.Links[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("links" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("links" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1AssetrulesUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AssetrulesUpdateRequest) UnmarshalBinary(b []byte) error {
	var res V1AssetrulesUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
