// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TeamsCreateSSOMappingRequest v1 teams create s s o mapping request
//
// swagger:model v1_teams.CreateSSOMappingRequest
type V1TeamsCreateSSOMappingRequest struct {

	// member role
	MemberRole string `json:"member_role,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// sso group name
	SsoGroupName string `json:"sso_group_name,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`
}

// Validate validates this v1 teams create s s o mapping request
func (m *V1TeamsCreateSSOMappingRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 teams create s s o mapping request based on context it is used
func (m *V1TeamsCreateSSOMappingRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TeamsCreateSSOMappingRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TeamsCreateSSOMappingRequest) UnmarshalBinary(b []byte) error {
	var res V1TeamsCreateSSOMappingRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
