// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TeamsUpdateTeamRequest v1 teams update team request
//
// swagger:model v1_teams.UpdateTeamRequest
type V1TeamsUpdateTeamRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// metadata
	Metadata any `json:"metadata,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this v1 teams update team request
func (m *V1TeamsUpdateTeamRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 teams update team request based on context it is used
func (m *V1TeamsUpdateTeamRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TeamsUpdateTeamRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TeamsUpdateTeamRequest) UnmarshalBinary(b []byte) error {
	var res V1TeamsUpdateTeamRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
