// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TeamsUpdateSSOMappingRequest v1 teams update s s o mapping request
//
// swagger:model v1_teams.UpdateSSOMappingRequest
type V1TeamsUpdateSSOMappingRequest struct {

	// member role
	MemberRole string `json:"member_role,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`
}

// Validate validates this v1 teams update s s o mapping request
func (m *V1TeamsUpdateSSOMappingRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 teams update s s o mapping request based on context it is used
func (m *V1TeamsUpdateSSOMappingRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TeamsUpdateSSOMappingRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TeamsUpdateSSOMappingRequest) UnmarshalBinary(b []byte) error {
	var res V1TeamsUpdateSSOMappingRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
