// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TeamsCreateTeamRequest v1 teams create team request
//
// swagger:model v1_teams.CreateTeamRequest
type V1TeamsCreateTeamRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v1 teams create team request
func (m *V1TeamsCreateTeamRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 teams create team request based on context it is used
func (m *V1TeamsCreateTeamRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TeamsCreateTeamRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TeamsCreateTeamRequest) UnmarshalBinary(b []byte) error {
	var res V1TeamsCreateTeamRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
