// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1TeamsAddMemberRequest v1 teams add member request
//
// swagger:model v1_teams.AddMemberRequest
type V1TeamsAddMemberRequest struct {

	// role
	Role string `json:"role,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this v1 teams add member request
func (m *V1TeamsAddMemberRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 teams add member request based on context it is used
func (m *V1TeamsAddMemberRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1TeamsAddMemberRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1TeamsAddMemberRequest) UnmarshalBinary(b []byte) error {
	var res V1TeamsAddMemberRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
