// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new auth API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new auth API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new auth API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for auth API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ConsumesMediaTypes = []string{mime}
	}
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/json"}
}

// WithContentTypeApplicationxWwwFormUrlencoded sets the Content-Type header to "application/x-www-form-urlencoded".
func WithContentTypeApplicationxWwwFormUrlencoded(r *runtime.ClientOperation) {
	r.ConsumesMediaTypes = []string{"application/x-www-form-urlencoded"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetAuthProviderCallback(params *GetAuthProviderCallbackParams, opts ...ClientOption) error

	GetAuthProviderLogin(params *GetAuthProviderLoginParams, opts ...ClientOption) error

	GetAuthProviders(params *GetAuthProvidersParams, opts ...ClientOption) (*GetAuthProvidersOK, error)

	PostOauthToken(params *PostOauthTokenParams, opts ...ClientOption) (*PostOauthTokenOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAuthProviderCallback handles o auth callback

Processes the OAuth callback from any provider
*/
func (a *Client) GetAuthProviderCallback(params *GetAuthProviderCallbackParams, opts ...ClientOption) error {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAuthProviderCallbackParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAuthProviderCallback",
		Method:             "GET",
		PathPattern:        "/auth/{provider}/callback",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAuthProviderCallbackReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	// no success response is defined: return nil

	return nil
}

/*
GetAuthProviderLogin initiates o auth login

Redirects the user to the OAuth provider for authentication
*/
func (a *Client) GetAuthProviderLogin(params *GetAuthProviderLoginParams, opts ...ClientOption) error {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAuthProviderLoginParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAuthProviderLogin",
		Method:             "GET",
		PathPattern:        "/auth/{provider}/login",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAuthProviderLoginReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	// no success response is defined: return nil

	return nil
}

/*
GetAuthProviders gets auth configuration

Returns the enabled auth providers without sensitive data
*/
func (a *Client) GetAuthProviders(params *GetAuthProvidersParams, opts ...ClientOption) (*GetAuthProvidersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAuthProvidersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAuthProviders",
		Method:             "GET",
		PathPattern:        "/auth-providers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAuthProvidersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAuthProvidersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAuthProviders: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostOauthToken os auth token endpoint

Handles authorization_code grants (with PKCE) and token exchange (RFC 8693).
*/
func (a *Client) PostOauthToken(params *PostOauthTokenParams, opts ...ClientOption) (*PostOauthTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostOauthTokenParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostOauthToken",
		Method:             "POST",
		PathPattern:        "/oauth/token",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostOauthTokenReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostOauthTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostOauthToken: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
