// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostOauthTokenReader is a Reader for the PostOauthToken structure.
type PostOauthTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOauthTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostOauthTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostOauthTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostOauthTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostOauthTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /oauth/token] PostOauthToken", response, response.Code())
	}
}

// NewPostOauthTokenOK creates a PostOauthTokenOK with default headers values
func NewPostOauthTokenOK() *PostOauthTokenOK {
	return &PostOauthTokenOK{}
}

/*
PostOauthTokenOK describes a response with status code 200, with default header values.

OK
*/
type PostOauthTokenOK struct {
	Payload *models.AuthTokenExchangeResponse
}

// IsSuccess returns true when this post oauth token o k response has a 2xx status code
func (o *PostOauthTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post oauth token o k response has a 3xx status code
func (o *PostOauthTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post oauth token o k response has a 4xx status code
func (o *PostOauthTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post oauth token o k response has a 5xx status code
func (o *PostOauthTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post oauth token o k response a status code equal to that given
func (o *PostOauthTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post oauth token o k response
func (o *PostOauthTokenOK) Code() int {
	return 200
}

func (o *PostOauthTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenOK %s", 200, payload)
}

func (o *PostOauthTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenOK %s", 200, payload)
}

func (o *PostOauthTokenOK) GetPayload() *models.AuthTokenExchangeResponse {
	return o.Payload
}

func (o *PostOauthTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthTokenExchangeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostOauthTokenBadRequest creates a PostOauthTokenBadRequest with default headers values
func NewPostOauthTokenBadRequest() *PostOauthTokenBadRequest {
	return &PostOauthTokenBadRequest{}
}

/*
PostOauthTokenBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostOauthTokenBadRequest struct {
	Payload *models.AuthOauthErrorResponse
}

// IsSuccess returns true when this post oauth token bad request response has a 2xx status code
func (o *PostOauthTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post oauth token bad request response has a 3xx status code
func (o *PostOauthTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post oauth token bad request response has a 4xx status code
func (o *PostOauthTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post oauth token bad request response has a 5xx status code
func (o *PostOauthTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post oauth token bad request response a status code equal to that given
func (o *PostOauthTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post oauth token bad request response
func (o *PostOauthTokenBadRequest) Code() int {
	return 400
}

func (o *PostOauthTokenBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenBadRequest %s", 400, payload)
}

func (o *PostOauthTokenBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenBadRequest %s", 400, payload)
}

func (o *PostOauthTokenBadRequest) GetPayload() *models.AuthOauthErrorResponse {
	return o.Payload
}

func (o *PostOauthTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthOauthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostOauthTokenUnauthorized creates a PostOauthTokenUnauthorized with default headers values
func NewPostOauthTokenUnauthorized() *PostOauthTokenUnauthorized {
	return &PostOauthTokenUnauthorized{}
}

/*
PostOauthTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostOauthTokenUnauthorized struct {
	Payload *models.AuthOauthErrorResponse
}

// IsSuccess returns true when this post oauth token unauthorized response has a 2xx status code
func (o *PostOauthTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post oauth token unauthorized response has a 3xx status code
func (o *PostOauthTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post oauth token unauthorized response has a 4xx status code
func (o *PostOauthTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post oauth token unauthorized response has a 5xx status code
func (o *PostOauthTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post oauth token unauthorized response a status code equal to that given
func (o *PostOauthTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post oauth token unauthorized response
func (o *PostOauthTokenUnauthorized) Code() int {
	return 401
}

func (o *PostOauthTokenUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenUnauthorized %s", 401, payload)
}

func (o *PostOauthTokenUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenUnauthorized %s", 401, payload)
}

func (o *PostOauthTokenUnauthorized) GetPayload() *models.AuthOauthErrorResponse {
	return o.Payload
}

func (o *PostOauthTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthOauthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostOauthTokenInternalServerError creates a PostOauthTokenInternalServerError with default headers values
func NewPostOauthTokenInternalServerError() *PostOauthTokenInternalServerError {
	return &PostOauthTokenInternalServerError{}
}

/*
PostOauthTokenInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostOauthTokenInternalServerError struct {
	Payload *models.AuthOauthErrorResponse
}

// IsSuccess returns true when this post oauth token internal server error response has a 2xx status code
func (o *PostOauthTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post oauth token internal server error response has a 3xx status code
func (o *PostOauthTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post oauth token internal server error response has a 4xx status code
func (o *PostOauthTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post oauth token internal server error response has a 5xx status code
func (o *PostOauthTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post oauth token internal server error response a status code equal to that given
func (o *PostOauthTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post oauth token internal server error response
func (o *PostOauthTokenInternalServerError) Code() int {
	return 500
}

func (o *PostOauthTokenInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenInternalServerError %s", 500, payload)
}

func (o *PostOauthTokenInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /oauth/token][%d] postOauthTokenInternalServerError %s", 500, payload)
}

func (o *PostOauthTokenInternalServerError) GetPayload() *models.AuthOauthErrorResponse {
	return o.Payload
}

func (o *PostOauthTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthOauthErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
