// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSsoTeamMappingsIDParams creates a new DeleteSsoTeamMappingsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSsoTeamMappingsIDParams() *DeleteSsoTeamMappingsIDParams {
	return &DeleteSsoTeamMappingsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSsoTeamMappingsIDParamsWithTimeout creates a new DeleteSsoTeamMappingsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteSsoTeamMappingsIDParamsWithTimeout(timeout time.Duration) *DeleteSsoTeamMappingsIDParams {
	return &DeleteSsoTeamMappingsIDParams{
		timeout: timeout,
	}
}

// NewDeleteSsoTeamMappingsIDParamsWithContext creates a new DeleteSsoTeamMappingsIDParams object
// with the ability to set a context for a request.
func NewDeleteSsoTeamMappingsIDParamsWithContext(ctx context.Context) *DeleteSsoTeamMappingsIDParams {
	return &DeleteSsoTeamMappingsIDParams{
		Context: ctx,
	}
}

// NewDeleteSsoTeamMappingsIDParamsWithHTTPClient creates a new DeleteSsoTeamMappingsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSsoTeamMappingsIDParamsWithHTTPClient(client *http.Client) *DeleteSsoTeamMappingsIDParams {
	return &DeleteSsoTeamMappingsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteSsoTeamMappingsIDParams contains all the parameters to send to the API endpoint

	for the delete sso team mappings ID operation.

	Typically these are written to a http.Request.
*/
type DeleteSsoTeamMappingsIDParams struct {

	/* ID.

	   SSO mapping ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSsoTeamMappingsIDParams) WithDefaults() *DeleteSsoTeamMappingsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSsoTeamMappingsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) WithTimeout(timeout time.Duration) *DeleteSsoTeamMappingsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) WithContext(ctx context.Context) *DeleteSsoTeamMappingsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) WithHTTPClient(client *http.Client) *DeleteSsoTeamMappingsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) WithID(id string) *DeleteSsoTeamMappingsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete sso team mappings ID params
func (o *DeleteSsoTeamMappingsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSsoTeamMappingsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
