// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// DeleteSsoTeamMappingsIDReader is a Reader for the DeleteSsoTeamMappingsID structure.
type DeleteSsoTeamMappingsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSsoTeamMappingsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSsoTeamMappingsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteSsoTeamMappingsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSsoTeamMappingsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /sso/team-mappings/{id}] DeleteSsoTeamMappingsID", response, response.Code())
	}
}

// NewDeleteSsoTeamMappingsIDOK creates a DeleteSsoTeamMappingsIDOK with default headers values
func NewDeleteSsoTeamMappingsIDOK() *DeleteSsoTeamMappingsIDOK {
	return &DeleteSsoTeamMappingsIDOK{}
}

/*
DeleteSsoTeamMappingsIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteSsoTeamMappingsIDOK struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this delete sso team mappings Id o k response has a 2xx status code
func (o *DeleteSsoTeamMappingsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete sso team mappings Id o k response has a 3xx status code
func (o *DeleteSsoTeamMappingsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete sso team mappings Id o k response has a 4xx status code
func (o *DeleteSsoTeamMappingsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete sso team mappings Id o k response has a 5xx status code
func (o *DeleteSsoTeamMappingsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete sso team mappings Id o k response a status code equal to that given
func (o *DeleteSsoTeamMappingsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete sso team mappings Id o k response
func (o *DeleteSsoTeamMappingsIDOK) Code() int {
	return 200
}

func (o *DeleteSsoTeamMappingsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdOK %s", 200, payload)
}

func (o *DeleteSsoTeamMappingsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdOK %s", 200, payload)
}

func (o *DeleteSsoTeamMappingsIDOK) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *DeleteSsoTeamMappingsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteSsoTeamMappingsIDNotFound creates a DeleteSsoTeamMappingsIDNotFound with default headers values
func NewDeleteSsoTeamMappingsIDNotFound() *DeleteSsoTeamMappingsIDNotFound {
	return &DeleteSsoTeamMappingsIDNotFound{}
}

/*
DeleteSsoTeamMappingsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteSsoTeamMappingsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete sso team mappings Id not found response has a 2xx status code
func (o *DeleteSsoTeamMappingsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete sso team mappings Id not found response has a 3xx status code
func (o *DeleteSsoTeamMappingsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete sso team mappings Id not found response has a 4xx status code
func (o *DeleteSsoTeamMappingsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete sso team mappings Id not found response has a 5xx status code
func (o *DeleteSsoTeamMappingsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete sso team mappings Id not found response a status code equal to that given
func (o *DeleteSsoTeamMappingsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete sso team mappings Id not found response
func (o *DeleteSsoTeamMappingsIDNotFound) Code() int {
	return 404
}

func (o *DeleteSsoTeamMappingsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdNotFound %s", 404, payload)
}

func (o *DeleteSsoTeamMappingsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdNotFound %s", 404, payload)
}

func (o *DeleteSsoTeamMappingsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteSsoTeamMappingsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteSsoTeamMappingsIDInternalServerError creates a DeleteSsoTeamMappingsIDInternalServerError with default headers values
func NewDeleteSsoTeamMappingsIDInternalServerError() *DeleteSsoTeamMappingsIDInternalServerError {
	return &DeleteSsoTeamMappingsIDInternalServerError{}
}

/*
DeleteSsoTeamMappingsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteSsoTeamMappingsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete sso team mappings Id internal server error response has a 2xx status code
func (o *DeleteSsoTeamMappingsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete sso team mappings Id internal server error response has a 3xx status code
func (o *DeleteSsoTeamMappingsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete sso team mappings Id internal server error response has a 4xx status code
func (o *DeleteSsoTeamMappingsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete sso team mappings Id internal server error response has a 5xx status code
func (o *DeleteSsoTeamMappingsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete sso team mappings Id internal server error response a status code equal to that given
func (o *DeleteSsoTeamMappingsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete sso team mappings Id internal server error response
func (o *DeleteSsoTeamMappingsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteSsoTeamMappingsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdInternalServerError %s", 500, payload)
}

func (o *DeleteSsoTeamMappingsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /sso/team-mappings/{id}][%d] deleteSsoTeamMappingsIdInternalServerError %s", 500, payload)
}

func (o *DeleteSsoTeamMappingsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteSsoTeamMappingsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
