// Code generated by go-swagger; DO NOT EDIT.

package sso

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetSsoTeamMappingsIDReader is a Reader for the GetSsoTeamMappingsID structure.
type GetSsoTeamMappingsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSsoTeamMappingsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSsoTeamMappingsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSsoTeamMappingsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSsoTeamMappingsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /sso/team-mappings/{id}] GetSsoTeamMappingsID", response, response.Code())
	}
}

// NewGetSsoTeamMappingsIDOK creates a GetSsoTeamMappingsIDOK with default headers values
func NewGetSsoTeamMappingsIDOK() *GetSsoTeamMappingsIDOK {
	return &GetSsoTeamMappingsIDOK{}
}

/*
GetSsoTeamMappingsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetSsoTeamMappingsIDOK struct {
	Payload *models.TeamSSOTeamMapping
}

// IsSuccess returns true when this get sso team mappings Id o k response has a 2xx status code
func (o *GetSsoTeamMappingsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get sso team mappings Id o k response has a 3xx status code
func (o *GetSsoTeamMappingsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get sso team mappings Id o k response has a 4xx status code
func (o *GetSsoTeamMappingsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get sso team mappings Id o k response has a 5xx status code
func (o *GetSsoTeamMappingsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get sso team mappings Id o k response a status code equal to that given
func (o *GetSsoTeamMappingsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get sso team mappings Id o k response
func (o *GetSsoTeamMappingsIDOK) Code() int {
	return 200
}

func (o *GetSsoTeamMappingsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdOK %s", 200, payload)
}

func (o *GetSsoTeamMappingsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdOK %s", 200, payload)
}

func (o *GetSsoTeamMappingsIDOK) GetPayload() *models.TeamSSOTeamMapping {
	return o.Payload
}

func (o *GetSsoTeamMappingsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TeamSSOTeamMapping)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSsoTeamMappingsIDNotFound creates a GetSsoTeamMappingsIDNotFound with default headers values
func NewGetSsoTeamMappingsIDNotFound() *GetSsoTeamMappingsIDNotFound {
	return &GetSsoTeamMappingsIDNotFound{}
}

/*
GetSsoTeamMappingsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetSsoTeamMappingsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get sso team mappings Id not found response has a 2xx status code
func (o *GetSsoTeamMappingsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get sso team mappings Id not found response has a 3xx status code
func (o *GetSsoTeamMappingsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get sso team mappings Id not found response has a 4xx status code
func (o *GetSsoTeamMappingsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get sso team mappings Id not found response has a 5xx status code
func (o *GetSsoTeamMappingsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get sso team mappings Id not found response a status code equal to that given
func (o *GetSsoTeamMappingsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get sso team mappings Id not found response
func (o *GetSsoTeamMappingsIDNotFound) Code() int {
	return 404
}

func (o *GetSsoTeamMappingsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdNotFound %s", 404, payload)
}

func (o *GetSsoTeamMappingsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdNotFound %s", 404, payload)
}

func (o *GetSsoTeamMappingsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetSsoTeamMappingsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSsoTeamMappingsIDInternalServerError creates a GetSsoTeamMappingsIDInternalServerError with default headers values
func NewGetSsoTeamMappingsIDInternalServerError() *GetSsoTeamMappingsIDInternalServerError {
	return &GetSsoTeamMappingsIDInternalServerError{}
}

/*
GetSsoTeamMappingsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetSsoTeamMappingsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get sso team mappings Id internal server error response has a 2xx status code
func (o *GetSsoTeamMappingsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get sso team mappings Id internal server error response has a 3xx status code
func (o *GetSsoTeamMappingsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get sso team mappings Id internal server error response has a 4xx status code
func (o *GetSsoTeamMappingsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get sso team mappings Id internal server error response has a 5xx status code
func (o *GetSsoTeamMappingsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get sso team mappings Id internal server error response a status code equal to that given
func (o *GetSsoTeamMappingsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get sso team mappings Id internal server error response
func (o *GetSsoTeamMappingsIDInternalServerError) Code() int {
	return 500
}

func (o *GetSsoTeamMappingsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdInternalServerError %s", 500, payload)
}

func (o *GetSsoTeamMappingsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings/{id}][%d] getSsoTeamMappingsIdInternalServerError %s", 500, payload)
}

func (o *GetSsoTeamMappingsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetSsoTeamMappingsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
