// Code generated by go-swagger; DO NOT EDIT.

package sso

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSsoTeamMappingsIDParams creates a new GetSsoTeamMappingsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSsoTeamMappingsIDParams() *GetSsoTeamMappingsIDParams {
	return &GetSsoTeamMappingsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSsoTeamMappingsIDParamsWithTimeout creates a new GetSsoTeamMappingsIDParams object
// with the ability to set a timeout on a request.
func NewGetSsoTeamMappingsIDParamsWithTimeout(timeout time.Duration) *GetSsoTeamMappingsIDParams {
	return &GetSsoTeamMappingsIDParams{
		timeout: timeout,
	}
}

// NewGetSsoTeamMappingsIDParamsWithContext creates a new GetSsoTeamMappingsIDParams object
// with the ability to set a context for a request.
func NewGetSsoTeamMappingsIDParamsWithContext(ctx context.Context) *GetSsoTeamMappingsIDParams {
	return &GetSsoTeamMappingsIDParams{
		Context: ctx,
	}
}

// NewGetSsoTeamMappingsIDParamsWithHTTPClient creates a new GetSsoTeamMappingsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSsoTeamMappingsIDParamsWithHTTPClient(client *http.Client) *GetSsoTeamMappingsIDParams {
	return &GetSsoTeamMappingsIDParams{
		HTTPClient: client,
	}
}

/*
GetSsoTeamMappingsIDParams contains all the parameters to send to the API endpoint

	for the get sso team mappings ID operation.

	Typically these are written to a http.Request.
*/
type GetSsoTeamMappingsIDParams struct {

	/* ID.

	   SSO mapping ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSsoTeamMappingsIDParams) WithDefaults() *GetSsoTeamMappingsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSsoTeamMappingsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) WithTimeout(timeout time.Duration) *GetSsoTeamMappingsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) WithContext(ctx context.Context) *GetSsoTeamMappingsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) WithHTTPClient(client *http.Client) *GetSsoTeamMappingsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) WithID(id string) *GetSsoTeamMappingsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sso team mappings ID params
func (o *GetSsoTeamMappingsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSsoTeamMappingsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
