// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetSsoTeamMappingsReader is a Reader for the GetSsoTeamMappings structure.
type GetSsoTeamMappingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSsoTeamMappingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSsoTeamMappingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetSsoTeamMappingsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /sso/team-mappings] GetSsoTeamMappings", response, response.Code())
	}
}

// NewGetSsoTeamMappingsOK creates a GetSsoTeamMappingsOK with default headers values
func NewGetSsoTeamMappingsOK() *GetSsoTeamMappingsOK {
	return &GetSsoTeamMappingsOK{}
}

/*
GetSsoTeamMappingsOK describes a response with status code 200, with default header values.

OK
*/
type GetSsoTeamMappingsOK struct {
	Payload *models.V1TeamsListSSOMappingsResponse
}

// IsSuccess returns true when this get sso team mappings o k response has a 2xx status code
func (o *GetSsoTeamMappingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get sso team mappings o k response has a 3xx status code
func (o *GetSsoTeamMappingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get sso team mappings o k response has a 4xx status code
func (o *GetSsoTeamMappingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get sso team mappings o k response has a 5xx status code
func (o *GetSsoTeamMappingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get sso team mappings o k response a status code equal to that given
func (o *GetSsoTeamMappingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get sso team mappings o k response
func (o *GetSsoTeamMappingsOK) Code() int {
	return 200
}

func (o *GetSsoTeamMappingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings][%d] getSsoTeamMappingsOK %s", 200, payload)
}

func (o *GetSsoTeamMappingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings][%d] getSsoTeamMappingsOK %s", 200, payload)
}

func (o *GetSsoTeamMappingsOK) GetPayload() *models.V1TeamsListSSOMappingsResponse {
	return o.Payload
}

func (o *GetSsoTeamMappingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsListSSOMappingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSsoTeamMappingsInternalServerError creates a GetSsoTeamMappingsInternalServerError with default headers values
func NewGetSsoTeamMappingsInternalServerError() *GetSsoTeamMappingsInternalServerError {
	return &GetSsoTeamMappingsInternalServerError{}
}

/*
GetSsoTeamMappingsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetSsoTeamMappingsInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get sso team mappings internal server error response has a 2xx status code
func (o *GetSsoTeamMappingsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get sso team mappings internal server error response has a 3xx status code
func (o *GetSsoTeamMappingsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get sso team mappings internal server error response has a 4xx status code
func (o *GetSsoTeamMappingsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get sso team mappings internal server error response has a 5xx status code
func (o *GetSsoTeamMappingsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get sso team mappings internal server error response a status code equal to that given
func (o *GetSsoTeamMappingsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get sso team mappings internal server error response
func (o *GetSsoTeamMappingsInternalServerError) Code() int {
	return 500
}

func (o *GetSsoTeamMappingsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings][%d] getSsoTeamMappingsInternalServerError %s", 500, payload)
}

func (o *GetSsoTeamMappingsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /sso/team-mappings][%d] getSsoTeamMappingsInternalServerError %s", 500, payload)
}

func (o *GetSsoTeamMappingsInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetSsoTeamMappingsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
