// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSsoTeamMappingsParams creates a new GetSsoTeamMappingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSsoTeamMappingsParams() *GetSsoTeamMappingsParams {
	return &GetSsoTeamMappingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSsoTeamMappingsParamsWithTimeout creates a new GetSsoTeamMappingsParams object
// with the ability to set a timeout on a request.
func NewGetSsoTeamMappingsParamsWithTimeout(timeout time.Duration) *GetSsoTeamMappingsParams {
	return &GetSsoTeamMappingsParams{
		timeout: timeout,
	}
}

// NewGetSsoTeamMappingsParamsWithContext creates a new GetSsoTeamMappingsParams object
// with the ability to set a context for a request.
func NewGetSsoTeamMappingsParamsWithContext(ctx context.Context) *GetSsoTeamMappingsParams {
	return &GetSsoTeamMappingsParams{
		Context: ctx,
	}
}

// NewGetSsoTeamMappingsParamsWithHTTPClient creates a new GetSsoTeamMappingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSsoTeamMappingsParamsWithHTTPClient(client *http.Client) *GetSsoTeamMappingsParams {
	return &GetSsoTeamMappingsParams{
		HTTPClient: client,
	}
}

/*
GetSsoTeamMappingsParams contains all the parameters to send to the API endpoint

	for the get sso team mappings operation.

	Typically these are written to a http.Request.
*/
type GetSsoTeamMappingsParams struct {

	/* Provider.

	   Filter by SSO provider
	*/
	Provider *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get sso team mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSsoTeamMappingsParams) WithDefaults() *GetSsoTeamMappingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get sso team mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSsoTeamMappingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) WithTimeout(timeout time.Duration) *GetSsoTeamMappingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) WithContext(ctx context.Context) *GetSsoTeamMappingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) WithHTTPClient(client *http.Client) *GetSsoTeamMappingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) WithProvider(provider *string) *GetSsoTeamMappingsParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the get sso team mappings params
func (o *GetSsoTeamMappingsParams) SetProvider(provider *string) {
	o.Provider = provider
}

// WriteToRequest writes these params to a swagger request
func (o *GetSsoTeamMappingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Provider != nil {

		// query param provider
		var qrProvider string

		if o.Provider != nil {
			qrProvider = *o.Provider
		}
		qProvider := qrProvider
		if qProvider != "" {

			if err := r.SetQueryParam("provider", qProvider); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
