// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// NewPostSsoTeamMappingsParams creates a new PostSsoTeamMappingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSsoTeamMappingsParams() *PostSsoTeamMappingsParams {
	return &PostSsoTeamMappingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSsoTeamMappingsParamsWithTimeout creates a new PostSsoTeamMappingsParams object
// with the ability to set a timeout on a request.
func NewPostSsoTeamMappingsParamsWithTimeout(timeout time.Duration) *PostSsoTeamMappingsParams {
	return &PostSsoTeamMappingsParams{
		timeout: timeout,
	}
}

// NewPostSsoTeamMappingsParamsWithContext creates a new PostSsoTeamMappingsParams object
// with the ability to set a context for a request.
func NewPostSsoTeamMappingsParamsWithContext(ctx context.Context) *PostSsoTeamMappingsParams {
	return &PostSsoTeamMappingsParams{
		Context: ctx,
	}
}

// NewPostSsoTeamMappingsParamsWithHTTPClient creates a new PostSsoTeamMappingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSsoTeamMappingsParamsWithHTTPClient(client *http.Client) *PostSsoTeamMappingsParams {
	return &PostSsoTeamMappingsParams{
		HTTPClient: client,
	}
}

/*
PostSsoTeamMappingsParams contains all the parameters to send to the API endpoint

	for the post sso team mappings operation.

	Typically these are written to a http.Request.
*/
type PostSsoTeamMappingsParams struct {

	/* Mapping.

	   SSO mapping creation request
	*/
	Mapping *models.V1TeamsCreateSSOMappingRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post sso team mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSsoTeamMappingsParams) WithDefaults() *PostSsoTeamMappingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post sso team mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSsoTeamMappingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) WithTimeout(timeout time.Duration) *PostSsoTeamMappingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) WithContext(ctx context.Context) *PostSsoTeamMappingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) WithHTTPClient(client *http.Client) *PostSsoTeamMappingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMapping adds the mapping to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) WithMapping(mapping *models.V1TeamsCreateSSOMappingRequest) *PostSsoTeamMappingsParams {
	o.SetMapping(mapping)
	return o
}

// SetMapping adds the mapping to the post sso team mappings params
func (o *PostSsoTeamMappingsParams) SetMapping(mapping *models.V1TeamsCreateSSOMappingRequest) {
	o.Mapping = mapping
}

// WriteToRequest writes these params to a swagger request
func (o *PostSsoTeamMappingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Mapping != nil {
		if err := r.SetBodyParam(o.Mapping); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
