// Code generated by go-swagger; DO NOT EDIT.

package sso

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// NewPutSsoTeamMappingsIDParams creates a new PutSsoTeamMappingsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutSsoTeamMappingsIDParams() *PutSsoTeamMappingsIDParams {
	return &PutSsoTeamMappingsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutSsoTeamMappingsIDParamsWithTimeout creates a new PutSsoTeamMappingsIDParams object
// with the ability to set a timeout on a request.
func NewPutSsoTeamMappingsIDParamsWithTimeout(timeout time.Duration) *PutSsoTeamMappingsIDParams {
	return &PutSsoTeamMappingsIDParams{
		timeout: timeout,
	}
}

// NewPutSsoTeamMappingsIDParamsWithContext creates a new PutSsoTeamMappingsIDParams object
// with the ability to set a context for a request.
func NewPutSsoTeamMappingsIDParamsWithContext(ctx context.Context) *PutSsoTeamMappingsIDParams {
	return &PutSsoTeamMappingsIDParams{
		Context: ctx,
	}
}

// NewPutSsoTeamMappingsIDParamsWithHTTPClient creates a new PutSsoTeamMappingsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutSsoTeamMappingsIDParamsWithHTTPClient(client *http.Client) *PutSsoTeamMappingsIDParams {
	return &PutSsoTeamMappingsIDParams{
		HTTPClient: client,
	}
}

/*
PutSsoTeamMappingsIDParams contains all the parameters to send to the API endpoint

	for the put sso team mappings ID operation.

	Typically these are written to a http.Request.
*/
type PutSsoTeamMappingsIDParams struct {

	/* ID.

	   SSO mapping ID
	*/
	ID string

	/* Mapping.

	   SSO mapping update request
	*/
	Mapping *models.V1TeamsUpdateSSOMappingRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSsoTeamMappingsIDParams) WithDefaults() *PutSsoTeamMappingsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put sso team mappings ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutSsoTeamMappingsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) WithTimeout(timeout time.Duration) *PutSsoTeamMappingsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) WithContext(ctx context.Context) *PutSsoTeamMappingsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) WithHTTPClient(client *http.Client) *PutSsoTeamMappingsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) WithID(id string) *PutSsoTeamMappingsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) SetID(id string) {
	o.ID = id
}

// WithMapping adds the mapping to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) WithMapping(mapping *models.V1TeamsUpdateSSOMappingRequest) *PutSsoTeamMappingsIDParams {
	o.SetMapping(mapping)
	return o
}

// SetMapping adds the mapping to the put sso team mappings ID params
func (o *PutSsoTeamMappingsIDParams) SetMapping(mapping *models.V1TeamsUpdateSSOMappingRequest) {
	o.Mapping = mapping
}

// WriteToRequest writes these params to a swagger request
func (o *PutSsoTeamMappingsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Mapping != nil {
		if err := r.SetBodyParam(o.Mapping); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
