// Code generated by go-swagger; DO NOT EDIT.

package sso

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new sso API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new sso API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new sso API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for sso API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteSsoTeamMappingsID(params *DeleteSsoTeamMappingsIDParams, opts ...ClientOption) (*DeleteSsoTeamMappingsIDOK, error)

	GetSsoTeamMappings(params *GetSsoTeamMappingsParams, opts ...ClientOption) (*GetSsoTeamMappingsOK, error)

	GetSsoTeamMappingsID(params *GetSsoTeamMappingsIDParams, opts ...ClientOption) (*GetSsoTeamMappingsIDOK, error)

	PostSsoTeamMappings(params *PostSsoTeamMappingsParams, opts ...ClientOption) (*PostSsoTeamMappingsCreated, error)

	PutSsoTeamMappingsID(params *PutSsoTeamMappingsIDParams, opts ...ClientOption) (*PutSsoTeamMappingsIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteSsoTeamMappingsID deletes an s s o team mapping

Delete an SSO team mapping by its ID
*/
func (a *Client) DeleteSsoTeamMappingsID(params *DeleteSsoTeamMappingsIDParams, opts ...ClientOption) (*DeleteSsoTeamMappingsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteSsoTeamMappingsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteSsoTeamMappingsID",
		Method:             "DELETE",
		PathPattern:        "/sso/team-mappings/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteSsoTeamMappingsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteSsoTeamMappingsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteSsoTeamMappingsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSsoTeamMappings lists s s o team mappings

Get a list of SSO group to team mappings
*/
func (a *Client) GetSsoTeamMappings(params *GetSsoTeamMappingsParams, opts ...ClientOption) (*GetSsoTeamMappingsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetSsoTeamMappingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSsoTeamMappings",
		Method:             "GET",
		PathPattern:        "/sso/team-mappings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSsoTeamMappingsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetSsoTeamMappingsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSsoTeamMappings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetSsoTeamMappingsID gets an s s o team mapping

Get an SSO team mapping by its ID
*/
func (a *Client) GetSsoTeamMappingsID(params *GetSsoTeamMappingsIDParams, opts ...ClientOption) (*GetSsoTeamMappingsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetSsoTeamMappingsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetSsoTeamMappingsID",
		Method:             "GET",
		PathPattern:        "/sso/team-mappings/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetSsoTeamMappingsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetSsoTeamMappingsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetSsoTeamMappingsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostSsoTeamMappings creates an s s o team mapping

Create a new SSO group to team mapping
*/
func (a *Client) PostSsoTeamMappings(params *PostSsoTeamMappingsParams, opts ...ClientOption) (*PostSsoTeamMappingsCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostSsoTeamMappingsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostSsoTeamMappings",
		Method:             "POST",
		PathPattern:        "/sso/team-mappings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostSsoTeamMappingsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostSsoTeamMappingsCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostSsoTeamMappings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutSsoTeamMappingsID updates an s s o team mapping

Update an SSO team mapping by its ID
*/
func (a *Client) PutSsoTeamMappingsID(params *PutSsoTeamMappingsIDParams, opts ...ClientOption) (*PutSsoTeamMappingsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutSsoTeamMappingsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutSsoTeamMappingsID",
		Method:             "PUT",
		PathPattern:        "/sso/team-mappings/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutSsoTeamMappingsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutSsoTeamMappingsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutSsoTeamMappingsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
