// Code generated by go-swagger; DO NOT EDIT.

package owners

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetOwnersSearchReader is a Reader for the GetOwnersSearch structure.
type GetOwnersSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOwnersSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetOwnersSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOwnersSearchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOwnersSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /owners/search] GetOwnersSearch", response, response.Code())
	}
}

// NewGetOwnersSearchOK creates a GetOwnersSearchOK with default headers values
func NewGetOwnersSearchOK() *GetOwnersSearchOK {
	return &GetOwnersSearchOK{}
}

/*
GetOwnersSearchOK describes a response with status code 200, with default header values.

OK
*/
type GetOwnersSearchOK struct {
	Payload *models.V1TeamsSearchOwnersResponse
}

// IsSuccess returns true when this get owners search o k response has a 2xx status code
func (o *GetOwnersSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get owners search o k response has a 3xx status code
func (o *GetOwnersSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get owners search o k response has a 4xx status code
func (o *GetOwnersSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get owners search o k response has a 5xx status code
func (o *GetOwnersSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get owners search o k response a status code equal to that given
func (o *GetOwnersSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get owners search o k response
func (o *GetOwnersSearchOK) Code() int {
	return 200
}

func (o *GetOwnersSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchOK %s", 200, payload)
}

func (o *GetOwnersSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchOK %s", 200, payload)
}

func (o *GetOwnersSearchOK) GetPayload() *models.V1TeamsSearchOwnersResponse {
	return o.Payload
}

func (o *GetOwnersSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsSearchOwnersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetOwnersSearchBadRequest creates a GetOwnersSearchBadRequest with default headers values
func NewGetOwnersSearchBadRequest() *GetOwnersSearchBadRequest {
	return &GetOwnersSearchBadRequest{}
}

/*
GetOwnersSearchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetOwnersSearchBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get owners search bad request response has a 2xx status code
func (o *GetOwnersSearchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get owners search bad request response has a 3xx status code
func (o *GetOwnersSearchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get owners search bad request response has a 4xx status code
func (o *GetOwnersSearchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get owners search bad request response has a 5xx status code
func (o *GetOwnersSearchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get owners search bad request response a status code equal to that given
func (o *GetOwnersSearchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get owners search bad request response
func (o *GetOwnersSearchBadRequest) Code() int {
	return 400
}

func (o *GetOwnersSearchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchBadRequest %s", 400, payload)
}

func (o *GetOwnersSearchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchBadRequest %s", 400, payload)
}

func (o *GetOwnersSearchBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetOwnersSearchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetOwnersSearchInternalServerError creates a GetOwnersSearchInternalServerError with default headers values
func NewGetOwnersSearchInternalServerError() *GetOwnersSearchInternalServerError {
	return &GetOwnersSearchInternalServerError{}
}

/*
GetOwnersSearchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetOwnersSearchInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get owners search internal server error response has a 2xx status code
func (o *GetOwnersSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get owners search internal server error response has a 3xx status code
func (o *GetOwnersSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get owners search internal server error response has a 4xx status code
func (o *GetOwnersSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get owners search internal server error response has a 5xx status code
func (o *GetOwnersSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get owners search internal server error response a status code equal to that given
func (o *GetOwnersSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get owners search internal server error response
func (o *GetOwnersSearchInternalServerError) Code() int {
	return 500
}

func (o *GetOwnersSearchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchInternalServerError %s", 500, payload)
}

func (o *GetOwnersSearchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /owners/search][%d] getOwnersSearchInternalServerError %s", 500, payload)
}

func (o *GetOwnersSearchInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetOwnersSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
