// Code generated by go-swagger; DO NOT EDIT.

package owners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOwnersSearchParams creates a new GetOwnersSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOwnersSearchParams() *GetOwnersSearchParams {
	return &GetOwnersSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOwnersSearchParamsWithTimeout creates a new GetOwnersSearchParams object
// with the ability to set a timeout on a request.
func NewGetOwnersSearchParamsWithTimeout(timeout time.Duration) *GetOwnersSearchParams {
	return &GetOwnersSearchParams{
		timeout: timeout,
	}
}

// NewGetOwnersSearchParamsWithContext creates a new GetOwnersSearchParams object
// with the ability to set a context for a request.
func NewGetOwnersSearchParamsWithContext(ctx context.Context) *GetOwnersSearchParams {
	return &GetOwnersSearchParams{
		Context: ctx,
	}
}

// NewGetOwnersSearchParamsWithHTTPClient creates a new GetOwnersSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOwnersSearchParamsWithHTTPClient(client *http.Client) *GetOwnersSearchParams {
	return &GetOwnersSearchParams{
		HTTPClient: client,
	}
}

/*
GetOwnersSearchParams contains all the parameters to send to the API endpoint

	for the get owners search operation.

	Typically these are written to a http.Request.
*/
type GetOwnersSearchParams struct {

	/* Limit.

	   Maximum number of results

	   Default: 20
	*/
	Limit *int64

	/* Q.

	   Search query
	*/
	Q string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get owners search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOwnersSearchParams) WithDefaults() *GetOwnersSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get owners search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOwnersSearchParams) SetDefaults() {
	var (
		limitDefault = int64(20)
	)

	val := GetOwnersSearchParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get owners search params
func (o *GetOwnersSearchParams) WithTimeout(timeout time.Duration) *GetOwnersSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get owners search params
func (o *GetOwnersSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get owners search params
func (o *GetOwnersSearchParams) WithContext(ctx context.Context) *GetOwnersSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get owners search params
func (o *GetOwnersSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get owners search params
func (o *GetOwnersSearchParams) WithHTTPClient(client *http.Client) *GetOwnersSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get owners search params
func (o *GetOwnersSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get owners search params
func (o *GetOwnersSearchParams) WithLimit(limit *int64) *GetOwnersSearchParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get owners search params
func (o *GetOwnersSearchParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithQ adds the q to the get owners search params
func (o *GetOwnersSearchParams) WithQ(q string) *GetOwnersSearchParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the get owners search params
func (o *GetOwnersSearchParams) SetQ(q string) {
	o.Q = q
}

// WriteToRequest writes these params to a swagger request
func (o *GetOwnersSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param q
	qrQ := o.Q
	qQ := qrQ
	if qQ != "" {

		if err := r.SetQueryParam("q", qQ); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
