package dagster

import (
	"encoding/json"
	"testing"

	pluginsdk "github.com/marmotdata/plugin-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func discover(t *testing.T, fake *fakeDagster, extra pluginsdk.RawConfig) *pluginsdk.DiscoveryResult {
	t.Helper()

	server := fake.start(t)

	config := pluginsdk.RawConfig{"host": server.URL}
	for key, value := range extra {
		config[key] = value
	}

	source := &Source{}
	result, err := source.Discover(t.Context(), config)
	require.NoError(t, err)
	require.NotNil(t, result)

	return result
}

func assetByName(t *testing.T, result *pluginsdk.DiscoveryResult, name string) pluginsdk.Asset {
	t.Helper()

	for _, asset := range result.Assets {
		if asset.Name != nil && *asset.Name == name {
			return asset
		}
	}
	t.Fatalf("no asset named %q in %d discovered assets", name, len(result.Assets))
	return pluginsdk.Asset{}
}

func hasEdge(result *pluginsdk.DiscoveryResult, source, target, edgeType string) bool {
	for _, edge := range result.Lineage {
		if edge.Source == source && edge.Target == target && edge.Type == edgeType {
			return true
		}
	}
	return false
}

func TestDiscover_CreatesAPipelinePerJob(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	etl := assetByName(t, result, "etl_job")
	assert.Equal(t, "Pipeline", etl.Type)
	assert.Equal(t, []string{"Dagster"}, etl.Providers)

	orders := assetByName(t, result, "orders_job")
	assert.Equal(t, "Pipeline", orders.Type)
}

func TestDiscover_SkipsDagstersImplicitAssetJob(t *testing.T) {
	// __ASSET_JOB is generated by Dagster, not written by a user, so it must
	// not turn up as a Pipeline.
	result := discover(t, newFakeDagster(), nil)

	for _, asset := range result.Assets {
		require.NotNil(t, asset.Name)
		assert.NotEqual(t, "__ASSET_JOB", *asset.Name)
	}
}

func TestDiscover_PipelineCarriesItsSchedule(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	schedules, ok := assetByName(t, result, "etl_job").Metadata["schedules"].([]map[string]any)
	require.True(t, ok, "expected a schedules list")
	require.Len(t, schedules, 1)

	assert.Equal(t, "etl_schedule", schedules[0]["name"])
	assert.Equal(t, "0 3 * * *", schedules[0]["cron_schedule"])
	assert.Equal(t, "RUNNING", schedules[0]["status"])
}

func TestDiscover_PipelineCarriesItsSensor(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	sensors, ok := assetByName(t, result, "etl_job").Metadata["sensors"].([]map[string]any)
	require.True(t, ok, "expected a sensors list")
	require.Len(t, sensors, 1)

	assert.Equal(t, "etl_sensor", sensors[0]["name"])
	assert.Equal(t, "STOPPED", sensors[0]["status"])
}

func TestDiscover_PipelineCarriesItsJobTags(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	tags, ok := assetByName(t, result, "etl_job").Metadata["tags"].(map[string]string)
	require.True(t, ok, "expected a tags map")

	assert.Equal(t, "data-platform", tags["team"])
}

func TestDiscover_PipelineDescriptionIsPromotedToTheAsset(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	etl := assetByName(t, result, "etl_job")
	require.NotNil(t, etl.Description)
	assert.Equal(t, "Op based ETL job.", *etl.Description)
}

func TestDiscover_PipelineWithoutADescriptionLeavesItUnset(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.Nil(t, assetByName(t, result, "orders_job").Description)
}

func TestDiscover_PipelineMarksAnAssetJob(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.Equal(t, false, assetByName(t, result, "etl_job").Metadata["is_asset_job"])
	assert.Equal(t, true, assetByName(t, result, "orders_job").Metadata["is_asset_job"])
}

func TestDiscover_PipelineLinksBackToDagster(t *testing.T) {
	fake := newFakeDagster()
	server := fake.start(t)

	source := &Source{}
	result, err := source.Discover(t.Context(), pluginsdk.RawConfig{"host": server.URL})
	require.NoError(t, err)

	etl := assetByName(t, result, "etl_job")
	require.Len(t, etl.ExternalLinks, 1)

	assert.Equal(t, "Open in Dagster", etl.ExternalLinks[0].Name)
	assert.Equal(t, server.URL+"/locations/defs.py/jobs/etl_job", etl.ExternalLinks[0].URL)
	assert.Equal(t, etl.ExternalLinks[0].URL, etl.Metadata["url"])
}

func TestDiscover_PipelineCountsItsOps(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.Equal(t, 3, assetByName(t, result, "etl_job").Metadata["op_count"])
}

func TestDiscover_PipelineSummarisesRecentRuns(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	etl := assetByName(t, result, "etl_job")
	assert.Equal(t, 1, etl.Metadata["run_count"])
	assert.Equal(t, "SUCCESS", etl.Metadata["last_run_status"])
	assert.Equal(t, float64(100), etl.Metadata["success_rate"])
	assert.Equal(t, "2026-09-08T07:41:44Z", etl.Metadata["last_run_at"])
}

func TestDiscover_PipelineWithNoRunsHasNoRunSummary(t *testing.T) {
	// A job that has never run must not report a zero success rate, which
	// would read as "always fails".
	result := discover(t, newFakeDagster(), nil)

	orders := assetByName(t, result, "orders_job")
	assert.NotContains(t, orders.Metadata, "run_count")
	assert.NotContains(t, orders.Metadata, "success_rate")
}

func TestDiscover_CreatesATaskPerOp(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	extract := assetByName(t, result, "etl_job/extract")
	assert.Equal(t, "Task", extract.Type)
	assert.Equal(t, "extract", extract.Metadata["op"])
	assert.Equal(t, "extract", extract.Metadata["handle_id"])
	assert.Equal(t, "etl_job", extract.Metadata["job"])
	assert.Equal(t, 0, extract.Metadata["input_count"])
	assert.Equal(t, 1, extract.Metadata["output_count"])
}

func TestDiscover_TaskDescriptionComesFromTheOpDefinition(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	transform := assetByName(t, result, "etl_job/transform")
	require.NotNil(t, transform.Description)
	assert.Equal(t, "Transform extracted records.", *transform.Description)
}

func TestDiscover_PipelineContainsItsTasks(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.True(t, hasEdge(result,
		"mrn://pipeline/dagster/etl_job",
		"mrn://task/dagster/etl_job-extract",
		"CONTAINS"))
}

func TestDiscover_TaskDependsOnTheOpFeedingItsInput(t *testing.T) {
	// transform reads extract's output, so the edge runs from extract to
	// transform and not the other way around.
	result := discover(t, newFakeDagster(), nil)

	assert.True(t, hasEdge(result,
		"mrn://task/dagster/etl_job-extract",
		"mrn://task/dagster/etl_job-transform",
		"DEPENDS_ON"))
	assert.False(t, hasEdge(result,
		"mrn://task/dagster/etl_job-transform",
		"mrn://task/dagster/etl_job-extract",
		"DEPENDS_ON"))
}

func TestDiscover_TaskWithNoInputsHasNoDependsOnEdge(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	for _, edge := range result.Lineage {
		if edge.Type == "DEPENDS_ON" {
			assert.NotEqual(t, "mrn://task/dagster/etl_job-extract", edge.Target)
		}
	}
}

func TestDiscover_CreatesADatasetPerSoftwareDefinedAsset(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	clean := assetByName(t, result, "clean_orders")
	assert.Equal(t, "Dataset", clean.Type)
	assert.Equal(t, []string{"Dagster"}, clean.Providers)
	assert.Equal(t, "duckdb", clean.Metadata["compute_kind"])
	assert.Equal(t, "staging", clean.Metadata["group"])
	assert.Equal(t, "defs.py", clean.Metadata["code_location"])
	assert.Equal(t, []string{"clean_orders"}, clean.Metadata["op_names"])
}

func TestDiscover_DatasetJobNamesExcludeTheImplicitAssetJob(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.Equal(t, []string{"orders_job"}, assetByName(t, result, "clean_orders").Metadata["job_names"])
}

func TestDiscover_DatasetColumnsComeFromTheTableSchemaEntry(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	raw, ok := assetByName(t, result, "clean_orders").Schema["columns"]
	require.True(t, ok, "expected a columns schema entry")

	var columns []pluginsdk.Column
	require.NoError(t, json.Unmarshal([]byte(raw), &columns))
	require.Len(t, columns, 2)

	assert.Equal(t, "id", columns[0].Name)
	assert.Equal(t, "integer", columns[0].DataType)
	assert.Equal(t, "Order identifier", columns[0].Description)
	assert.True(t, columns[0].Nullable)
	assert.Equal(t, "amount", columns[1].Name)
	assert.Equal(t, "double", columns[1].DataType)
}

func TestDiscover_DatasetWithoutATableSchemaHasNoColumns(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.NotContains(t, assetByName(t, result, "raw_orders").Schema, "columns")
}

func TestDiscover_DatasetFlattensDagstersMetadataEntries(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	metadata := assetByName(t, result, "clean_orders").Metadata
	assert.Equal(t, "analytics.staging.clean_orders", metadata["dagster_table_name"])
	assert.Equal(t, "https://example.com/docs/clean_orders", metadata["docs_url"])
	assert.Equal(t, "/data/staging/clean_orders.parquet", metadata["source_path"])
	assert.Equal(t, `{"rows": 2}`, metadata["profile"])
}

func TestDiscover_DatasetKeepsItsOwnDescriptionOverAMetadataEntry(t *testing.T) {
	// A user label could collide with a field this plugin documents, so the
	// documented field has to win.
	result := discover(t, newFakeDagster(), nil)

	assert.Equal(t, "Cleaned orders stored in DuckDB.", assetByName(t, result, "clean_orders").Metadata["description"])
}

func TestDiscover_DatasetRecordsItsLastMaterialization(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	metadata := assetByName(t, result, "clean_orders").Metadata
	assert.Equal(t, "2026-09-08T07:41:47Z", metadata["last_materialized_at"])
	assert.Equal(t, "05c1267f-d0b5-496c-a5dc-17aa462775f1", metadata["last_materialization_run"])
}

func TestDiscover_DatasetLinksBackToDagster(t *testing.T) {
	fake := newFakeDagster()
	server := fake.start(t)

	source := &Source{}
	result, err := source.Discover(t.Context(), pluginsdk.RawConfig{"host": server.URL})
	require.NoError(t, err)

	clean := assetByName(t, result, "clean_orders")
	require.Len(t, clean.ExternalLinks, 1)
	assert.Equal(t, server.URL+"/assets/clean_orders", clean.ExternalLinks[0].URL)
}

func TestDiscover_DatasetFeedsItsDownstreamDataset(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.True(t, hasEdge(result,
		"mrn://dataset/dagster/raw_orders",
		"mrn://dataset/dagster/clean_orders",
		"FEEDS"))
	assert.True(t, hasEdge(result,
		"mrn://dataset/dagster/clean_orders",
		"mrn://dataset/dagster/order_metrics",
		"FEEDS"))
}

func TestDiscover_PipelineProducesTheDatasetsItMaterialises(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	assert.True(t, hasEdge(result,
		"mrn://pipeline/dagster/orders_job",
		"mrn://dataset/dagster/clean_orders",
		"PRODUCES"))
}

func TestDiscover_DatasetProducesTheWarehouseTableItWrites(t *testing.T) {
	// clean_orders is computed by DuckDB and names its table, so it points at
	// the table the DuckDB plugin would create.
	result := discover(t, newFakeDagster(), nil)

	assert.True(t, hasEdge(result,
		"mrn://dataset/dagster/clean_orders",
		"mrn://table/duckdb/clean_orders",
		"PRODUCES"))
}

func TestDiscover_DatasetWithoutAWarehouseHasNoTableEdge(t *testing.T) {
	// raw_orders declares no compute kind, so nothing says where it lands and
	// no table edge may be guessed for it.
	result := discover(t, newFakeDagster(), nil)

	for _, edge := range result.Lineage {
		if edge.Source == "mrn://dataset/dagster/raw_orders" {
			assert.Equal(t, "FEEDS", edge.Type)
		}
	}
}

func TestDiscover_ConvertsRunsIntoRunHistory(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	require.Len(t, result.RunHistory, 1)
	history := result.RunHistory[0]

	assert.Equal(t, "mrn://pipeline/dagster/etl_job", history.AssetMRN)
	require.Len(t, history.Runs, 2)

	assert.Equal(t, "START", history.Runs[0].EventType)
	assert.Equal(t, "COMPLETE", history.Runs[1].EventType)
	assert.Equal(t, "0a85d76d-cf75-4fa6-af87-8815e349db45", history.Runs[0].RunID)
	assert.Equal(t, "dagster", history.Runs[0].JobNamespace)
	assert.Equal(t, "etl_job", history.Runs[0].JobName)
}

func TestDiscover_RunHistoryEventsAreTimedFromTheRun(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	runs := result.RunHistory[0].Runs
	assert.Equal(t, "2026-09-08T07:41:44Z", runs[0].EventTime.UTC().Format("2006-01-02T15:04:05Z"))
	assert.Equal(t, "2026-09-08T07:41:46Z", runs[1].EventTime.UTC().Format("2006-01-02T15:04:05Z"))
}

func TestDiscover_RunFacetsCarryStepCountsAndTags(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	facets := result.RunHistory[0].Runs[1].RunFacets
	assert.Equal(t, "SUCCESS", facets["status"])
	assert.Equal(t, 3, facets["step_count"])
	assert.Equal(t, 3, facets["step_success_count"])
	assert.Equal(t, 0, facets["step_failure_count"])

	tags, ok := facets["tags"].(map[string]string)
	require.True(t, ok)
	assert.Equal(t, "data-platform", tags["team"])
}

func TestDiscover_IncludeOpsFalseSkipsTasks(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{"include_ops": false})

	for _, asset := range result.Assets {
		assert.NotEqual(t, "Task", asset.Type)
	}
	for _, edge := range result.Lineage {
		assert.NotEqual(t, "CONTAINS", edge.Type)
	}
}

func TestDiscover_IncludeAssetsFalseSkipsDatasets(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{"include_assets": false})

	for _, asset := range result.Assets {
		assert.NotEqual(t, "Dataset", asset.Type)
	}
}

func TestDiscover_IncludeRunHistoryFalseSkipsRuns(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{"include_run_history": false})

	assert.Empty(t, result.RunHistory)
	assert.NotContains(t, assetByName(t, result, "etl_job").Metadata, "last_run_status")
}

func TestDiscover_CodeLocationsSelectsOnlyTheListedLocation(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{"code_locations": []any{"other"}})

	assert.Empty(t, result.Assets)
}

func TestDiscover_CodeLocationsAcceptsTheMatchingLocation(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{"code_locations": []any{"defs.py"}})

	assert.NotEmpty(t, result.Assets)
}

func TestDiscover_SendsTheCloudTokenHeader(t *testing.T) {
	fake := newFakeDagster()
	server := fake.start(t)

	source := &Source{}
	_, err := source.Discover(t.Context(), pluginsdk.RawConfig{"host": server.URL, "token": "secret-token"})
	require.NoError(t, err)

	require.NotEmpty(t, fake.tokens)
	for _, token := range fake.tokens {
		assert.Equal(t, "secret-token", token)
	}
}

func TestDiscover_SendsNoTokenHeaderWhenUnset(t *testing.T) {
	fake := newFakeDagster()
	server := fake.start(t)

	source := &Source{}
	_, err := source.Discover(t.Context(), pluginsdk.RawConfig{"host": server.URL})
	require.NoError(t, err)

	require.NotEmpty(t, fake.tokens)
	assert.Equal(t, "", fake.tokens[0])
}

func TestDiscover_UnreachableHostFails(t *testing.T) {
	source := &Source{}
	_, err := source.Discover(t.Context(), pluginsdk.RawConfig{"host": "http://127.0.0.1:1"})
	assert.Error(t, err)
}

func TestDiscover_EveryAssetCarriesADagsterSource(t *testing.T) {
	result := discover(t, newFakeDagster(), nil)

	require.NotEmpty(t, result.Assets)
	for _, asset := range result.Assets {
		require.Len(t, asset.Sources, 1)
		assert.Equal(t, "Dagster", asset.Sources[0].Name)
		assert.Equal(t, 1, asset.Sources[0].Priority)
	}
}

func TestDiscover_InterpolatesConfiguredTags(t *testing.T) {
	result := discover(t, newFakeDagster(), pluginsdk.RawConfig{
		"tags": []any{"dagster", "location:${code_location}"},
	})

	assert.Contains(t, assetByName(t, result, "clean_orders").Tags, "location:defs.py")
}
