// Code generated by go-swagger; DO NOT EDIT.

package tags

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// DeleteTagsIDReader is a Reader for the DeleteTagsID structure.
type DeleteTagsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTagsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteTagsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteTagsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteTagsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteTagsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /tags/{id}] DeleteTagsID", response, response.Code())
	}
}

// NewDeleteTagsIDNoContent creates a DeleteTagsIDNoContent with default headers values
func NewDeleteTagsIDNoContent() *DeleteTagsIDNoContent {
	return &DeleteTagsIDNoContent{}
}

/*
DeleteTagsIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteTagsIDNoContent struct {
}

// IsSuccess returns true when this delete tags Id no content response has a 2xx status code
func (o *DeleteTagsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete tags Id no content response has a 3xx status code
func (o *DeleteTagsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tags Id no content response has a 4xx status code
func (o *DeleteTagsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete tags Id no content response has a 5xx status code
func (o *DeleteTagsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tags Id no content response a status code equal to that given
func (o *DeleteTagsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete tags Id no content response
func (o *DeleteTagsIDNoContent) Code() int {
	return 204
}

func (o *DeleteTagsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdNoContent", 204)
}

func (o *DeleteTagsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdNoContent", 204)
}

func (o *DeleteTagsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTagsIDBadRequest creates a DeleteTagsIDBadRequest with default headers values
func NewDeleteTagsIDBadRequest() *DeleteTagsIDBadRequest {
	return &DeleteTagsIDBadRequest{}
}

/*
DeleteTagsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteTagsIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete tags Id bad request response has a 2xx status code
func (o *DeleteTagsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete tags Id bad request response has a 3xx status code
func (o *DeleteTagsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tags Id bad request response has a 4xx status code
func (o *DeleteTagsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete tags Id bad request response has a 5xx status code
func (o *DeleteTagsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tags Id bad request response a status code equal to that given
func (o *DeleteTagsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete tags Id bad request response
func (o *DeleteTagsIDBadRequest) Code() int {
	return 400
}

func (o *DeleteTagsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdBadRequest %s", 400, payload)
}

func (o *DeleteTagsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdBadRequest %s", 400, payload)
}

func (o *DeleteTagsIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteTagsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTagsIDNotFound creates a DeleteTagsIDNotFound with default headers values
func NewDeleteTagsIDNotFound() *DeleteTagsIDNotFound {
	return &DeleteTagsIDNotFound{}
}

/*
DeleteTagsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteTagsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete tags Id not found response has a 2xx status code
func (o *DeleteTagsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete tags Id not found response has a 3xx status code
func (o *DeleteTagsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tags Id not found response has a 4xx status code
func (o *DeleteTagsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete tags Id not found response has a 5xx status code
func (o *DeleteTagsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete tags Id not found response a status code equal to that given
func (o *DeleteTagsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete tags Id not found response
func (o *DeleteTagsIDNotFound) Code() int {
	return 404
}

func (o *DeleteTagsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdNotFound %s", 404, payload)
}

func (o *DeleteTagsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdNotFound %s", 404, payload)
}

func (o *DeleteTagsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteTagsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTagsIDInternalServerError creates a DeleteTagsIDInternalServerError with default headers values
func NewDeleteTagsIDInternalServerError() *DeleteTagsIDInternalServerError {
	return &DeleteTagsIDInternalServerError{}
}

/*
DeleteTagsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteTagsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete tags Id internal server error response has a 2xx status code
func (o *DeleteTagsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete tags Id internal server error response has a 3xx status code
func (o *DeleteTagsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete tags Id internal server error response has a 4xx status code
func (o *DeleteTagsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete tags Id internal server error response has a 5xx status code
func (o *DeleteTagsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete tags Id internal server error response a status code equal to that given
func (o *DeleteTagsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete tags Id internal server error response
func (o *DeleteTagsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteTagsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdInternalServerError %s", 500, payload)
}

func (o *DeleteTagsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tags/{id}][%d] deleteTagsIdInternalServerError %s", 500, payload)
}

func (o *DeleteTagsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteTagsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
