// Code generated by go-swagger; DO NOT EDIT.

package tags

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTagsIDParams creates a new DeleteTagsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTagsIDParams() *DeleteTagsIDParams {
	return &DeleteTagsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTagsIDParamsWithTimeout creates a new DeleteTagsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteTagsIDParamsWithTimeout(timeout time.Duration) *DeleteTagsIDParams {
	return &DeleteTagsIDParams{
		timeout: timeout,
	}
}

// NewDeleteTagsIDParamsWithContext creates a new DeleteTagsIDParams object
// with the ability to set a context for a request.
func NewDeleteTagsIDParamsWithContext(ctx context.Context) *DeleteTagsIDParams {
	return &DeleteTagsIDParams{
		Context: ctx,
	}
}

// NewDeleteTagsIDParamsWithHTTPClient creates a new DeleteTagsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTagsIDParamsWithHTTPClient(client *http.Client) *DeleteTagsIDParams {
	return &DeleteTagsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteTagsIDParams contains all the parameters to send to the API endpoint

	for the delete tags ID operation.

	Typically these are written to a http.Request.
*/
type DeleteTagsIDParams struct {

	/* ID.

	   Tag ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete tags ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTagsIDParams) WithDefaults() *DeleteTagsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete tags ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTagsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete tags ID params
func (o *DeleteTagsIDParams) WithTimeout(timeout time.Duration) *DeleteTagsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete tags ID params
func (o *DeleteTagsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete tags ID params
func (o *DeleteTagsIDParams) WithContext(ctx context.Context) *DeleteTagsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete tags ID params
func (o *DeleteTagsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete tags ID params
func (o *DeleteTagsIDParams) WithHTTPClient(client *http.Client) *DeleteTagsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete tags ID params
func (o *DeleteTagsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete tags ID params
func (o *DeleteTagsIDParams) WithID(id string) *DeleteTagsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete tags ID params
func (o *DeleteTagsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTagsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
