// Code generated by go-swagger; DO NOT EDIT.

package tags

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PutTagsIDReader is a Reader for the PutTagsID structure.
type PutTagsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTagsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutTagsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutTagsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutTagsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutTagsIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutTagsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /tags/{id}] PutTagsID", response, response.Code())
	}
}

// NewPutTagsIDOK creates a PutTagsIDOK with default headers values
func NewPutTagsIDOK() *PutTagsIDOK {
	return &PutTagsIDOK{}
}

/*
PutTagsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutTagsIDOK struct {
	Payload *models.GithubComMarmotdataMarmotInternalCoreTagTag
}

// IsSuccess returns true when this put tags Id o k response has a 2xx status code
func (o *PutTagsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put tags Id o k response has a 3xx status code
func (o *PutTagsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put tags Id o k response has a 4xx status code
func (o *PutTagsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put tags Id o k response has a 5xx status code
func (o *PutTagsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put tags Id o k response a status code equal to that given
func (o *PutTagsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put tags Id o k response
func (o *PutTagsIDOK) Code() int {
	return 200
}

func (o *PutTagsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdOK %s", 200, payload)
}

func (o *PutTagsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdOK %s", 200, payload)
}

func (o *PutTagsIDOK) GetPayload() *models.GithubComMarmotdataMarmotInternalCoreTagTag {
	return o.Payload
}

func (o *PutTagsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalCoreTagTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTagsIDBadRequest creates a PutTagsIDBadRequest with default headers values
func NewPutTagsIDBadRequest() *PutTagsIDBadRequest {
	return &PutTagsIDBadRequest{}
}

/*
PutTagsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutTagsIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put tags Id bad request response has a 2xx status code
func (o *PutTagsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put tags Id bad request response has a 3xx status code
func (o *PutTagsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put tags Id bad request response has a 4xx status code
func (o *PutTagsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put tags Id bad request response has a 5xx status code
func (o *PutTagsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put tags Id bad request response a status code equal to that given
func (o *PutTagsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put tags Id bad request response
func (o *PutTagsIDBadRequest) Code() int {
	return 400
}

func (o *PutTagsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdBadRequest %s", 400, payload)
}

func (o *PutTagsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdBadRequest %s", 400, payload)
}

func (o *PutTagsIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTagsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTagsIDNotFound creates a PutTagsIDNotFound with default headers values
func NewPutTagsIDNotFound() *PutTagsIDNotFound {
	return &PutTagsIDNotFound{}
}

/*
PutTagsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutTagsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put tags Id not found response has a 2xx status code
func (o *PutTagsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put tags Id not found response has a 3xx status code
func (o *PutTagsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put tags Id not found response has a 4xx status code
func (o *PutTagsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put tags Id not found response has a 5xx status code
func (o *PutTagsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put tags Id not found response a status code equal to that given
func (o *PutTagsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put tags Id not found response
func (o *PutTagsIDNotFound) Code() int {
	return 404
}

func (o *PutTagsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdNotFound %s", 404, payload)
}

func (o *PutTagsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdNotFound %s", 404, payload)
}

func (o *PutTagsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTagsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTagsIDConflict creates a PutTagsIDConflict with default headers values
func NewPutTagsIDConflict() *PutTagsIDConflict {
	return &PutTagsIDConflict{}
}

/*
PutTagsIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutTagsIDConflict struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put tags Id conflict response has a 2xx status code
func (o *PutTagsIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put tags Id conflict response has a 3xx status code
func (o *PutTagsIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put tags Id conflict response has a 4xx status code
func (o *PutTagsIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put tags Id conflict response has a 5xx status code
func (o *PutTagsIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put tags Id conflict response a status code equal to that given
func (o *PutTagsIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put tags Id conflict response
func (o *PutTagsIDConflict) Code() int {
	return 409
}

func (o *PutTagsIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdConflict %s", 409, payload)
}

func (o *PutTagsIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdConflict %s", 409, payload)
}

func (o *PutTagsIDConflict) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTagsIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTagsIDInternalServerError creates a PutTagsIDInternalServerError with default headers values
func NewPutTagsIDInternalServerError() *PutTagsIDInternalServerError {
	return &PutTagsIDInternalServerError{}
}

/*
PutTagsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutTagsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put tags Id internal server error response has a 2xx status code
func (o *PutTagsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put tags Id internal server error response has a 3xx status code
func (o *PutTagsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put tags Id internal server error response has a 4xx status code
func (o *PutTagsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put tags Id internal server error response has a 5xx status code
func (o *PutTagsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put tags Id internal server error response a status code equal to that given
func (o *PutTagsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put tags Id internal server error response
func (o *PutTagsIDInternalServerError) Code() int {
	return 500
}

func (o *PutTagsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdInternalServerError %s", 500, payload)
}

func (o *PutTagsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /tags/{id}][%d] putTagsIdInternalServerError %s", 500, payload)
}

func (o *PutTagsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTagsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
