// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// DeleteTeamsIDMembersUserIDReader is a Reader for the DeleteTeamsIDMembersUserID structure.
type DeleteTeamsIDMembersUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTeamsIDMembersUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTeamsIDMembersUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteTeamsIDMembersUserIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteTeamsIDMembersUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /teams/{id}/members/{userId}] DeleteTeamsIDMembersUserID", response, response.Code())
	}
}

// NewDeleteTeamsIDMembersUserIDOK creates a DeleteTeamsIDMembersUserIDOK with default headers values
func NewDeleteTeamsIDMembersUserIDOK() *DeleteTeamsIDMembersUserIDOK {
	return &DeleteTeamsIDMembersUserIDOK{}
}

/*
DeleteTeamsIDMembersUserIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteTeamsIDMembersUserIDOK struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this delete teams Id members user Id o k response has a 2xx status code
func (o *DeleteTeamsIDMembersUserIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete teams Id members user Id o k response has a 3xx status code
func (o *DeleteTeamsIDMembersUserIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete teams Id members user Id o k response has a 4xx status code
func (o *DeleteTeamsIDMembersUserIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete teams Id members user Id o k response has a 5xx status code
func (o *DeleteTeamsIDMembersUserIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete teams Id members user Id o k response a status code equal to that given
func (o *DeleteTeamsIDMembersUserIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete teams Id members user Id o k response
func (o *DeleteTeamsIDMembersUserIDOK) Code() int {
	return 200
}

func (o *DeleteTeamsIDMembersUserIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdOK %s", 200, payload)
}

func (o *DeleteTeamsIDMembersUserIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdOK %s", 200, payload)
}

func (o *DeleteTeamsIDMembersUserIDOK) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *DeleteTeamsIDMembersUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTeamsIDMembersUserIDNotFound creates a DeleteTeamsIDMembersUserIDNotFound with default headers values
func NewDeleteTeamsIDMembersUserIDNotFound() *DeleteTeamsIDMembersUserIDNotFound {
	return &DeleteTeamsIDMembersUserIDNotFound{}
}

/*
DeleteTeamsIDMembersUserIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteTeamsIDMembersUserIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete teams Id members user Id not found response has a 2xx status code
func (o *DeleteTeamsIDMembersUserIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete teams Id members user Id not found response has a 3xx status code
func (o *DeleteTeamsIDMembersUserIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete teams Id members user Id not found response has a 4xx status code
func (o *DeleteTeamsIDMembersUserIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete teams Id members user Id not found response has a 5xx status code
func (o *DeleteTeamsIDMembersUserIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete teams Id members user Id not found response a status code equal to that given
func (o *DeleteTeamsIDMembersUserIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete teams Id members user Id not found response
func (o *DeleteTeamsIDMembersUserIDNotFound) Code() int {
	return 404
}

func (o *DeleteTeamsIDMembersUserIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdNotFound %s", 404, payload)
}

func (o *DeleteTeamsIDMembersUserIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdNotFound %s", 404, payload)
}

func (o *DeleteTeamsIDMembersUserIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteTeamsIDMembersUserIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteTeamsIDMembersUserIDInternalServerError creates a DeleteTeamsIDMembersUserIDInternalServerError with default headers values
func NewDeleteTeamsIDMembersUserIDInternalServerError() *DeleteTeamsIDMembersUserIDInternalServerError {
	return &DeleteTeamsIDMembersUserIDInternalServerError{}
}

/*
DeleteTeamsIDMembersUserIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteTeamsIDMembersUserIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this delete teams Id members user Id internal server error response has a 2xx status code
func (o *DeleteTeamsIDMembersUserIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete teams Id members user Id internal server error response has a 3xx status code
func (o *DeleteTeamsIDMembersUserIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete teams Id members user Id internal server error response has a 4xx status code
func (o *DeleteTeamsIDMembersUserIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete teams Id members user Id internal server error response has a 5xx status code
func (o *DeleteTeamsIDMembersUserIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete teams Id members user Id internal server error response a status code equal to that given
func (o *DeleteTeamsIDMembersUserIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete teams Id members user Id internal server error response
func (o *DeleteTeamsIDMembersUserIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteTeamsIDMembersUserIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdInternalServerError %s", 500, payload)
}

func (o *DeleteTeamsIDMembersUserIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{id}/members/{userId}][%d] deleteTeamsIdMembersUserIdInternalServerError %s", 500, payload)
}

func (o *DeleteTeamsIDMembersUserIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *DeleteTeamsIDMembersUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
