// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetTeamsIDMembersReader is a Reader for the GetTeamsIDMembers structure.
type GetTeamsIDMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamsIDMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamsIDMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetTeamsIDMembersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /teams/{id}/members] GetTeamsIDMembers", response, response.Code())
	}
}

// NewGetTeamsIDMembersOK creates a GetTeamsIDMembersOK with default headers values
func NewGetTeamsIDMembersOK() *GetTeamsIDMembersOK {
	return &GetTeamsIDMembersOK{}
}

/*
GetTeamsIDMembersOK describes a response with status code 200, with default header values.

OK
*/
type GetTeamsIDMembersOK struct {
	Payload *models.V1TeamsListMembersResponse
}

// IsSuccess returns true when this get teams Id members o k response has a 2xx status code
func (o *GetTeamsIDMembersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get teams Id members o k response has a 3xx status code
func (o *GetTeamsIDMembersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get teams Id members o k response has a 4xx status code
func (o *GetTeamsIDMembersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get teams Id members o k response has a 5xx status code
func (o *GetTeamsIDMembersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get teams Id members o k response a status code equal to that given
func (o *GetTeamsIDMembersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get teams Id members o k response
func (o *GetTeamsIDMembersOK) Code() int {
	return 200
}

func (o *GetTeamsIDMembersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/members][%d] getTeamsIdMembersOK %s", 200, payload)
}

func (o *GetTeamsIDMembersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/members][%d] getTeamsIdMembersOK %s", 200, payload)
}

func (o *GetTeamsIDMembersOK) GetPayload() *models.V1TeamsListMembersResponse {
	return o.Payload
}

func (o *GetTeamsIDMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsListMembersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTeamsIDMembersInternalServerError creates a GetTeamsIDMembersInternalServerError with default headers values
func NewGetTeamsIDMembersInternalServerError() *GetTeamsIDMembersInternalServerError {
	return &GetTeamsIDMembersInternalServerError{}
}

/*
GetTeamsIDMembersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetTeamsIDMembersInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get teams Id members internal server error response has a 2xx status code
func (o *GetTeamsIDMembersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get teams Id members internal server error response has a 3xx status code
func (o *GetTeamsIDMembersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get teams Id members internal server error response has a 4xx status code
func (o *GetTeamsIDMembersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get teams Id members internal server error response has a 5xx status code
func (o *GetTeamsIDMembersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get teams Id members internal server error response a status code equal to that given
func (o *GetTeamsIDMembersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get teams Id members internal server error response
func (o *GetTeamsIDMembersInternalServerError) Code() int {
	return 500
}

func (o *GetTeamsIDMembersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/members][%d] getTeamsIdMembersInternalServerError %s", 500, payload)
}

func (o *GetTeamsIDMembersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}/members][%d] getTeamsIdMembersInternalServerError %s", 500, payload)
}

func (o *GetTeamsIDMembersInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetTeamsIDMembersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
