// Code generated by go-swagger; DO NOT EDIT.

package teams

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetTeamsIDReader is a Reader for the GetTeamsID structure.
type GetTeamsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTeamsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetTeamsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTeamsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTeamsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /teams/{id}] GetTeamsID", response, response.Code())
	}
}

// NewGetTeamsIDOK creates a GetTeamsIDOK with default headers values
func NewGetTeamsIDOK() *GetTeamsIDOK {
	return &GetTeamsIDOK{}
}

/*
GetTeamsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetTeamsIDOK struct {
	Payload *models.TeamTeam
}

// IsSuccess returns true when this get teams Id o k response has a 2xx status code
func (o *GetTeamsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get teams Id o k response has a 3xx status code
func (o *GetTeamsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get teams Id o k response has a 4xx status code
func (o *GetTeamsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get teams Id o k response has a 5xx status code
func (o *GetTeamsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get teams Id o k response a status code equal to that given
func (o *GetTeamsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get teams Id o k response
func (o *GetTeamsIDOK) Code() int {
	return 200
}

func (o *GetTeamsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdOK %s", 200, payload)
}

func (o *GetTeamsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdOK %s", 200, payload)
}

func (o *GetTeamsIDOK) GetPayload() *models.TeamTeam {
	return o.Payload
}

func (o *GetTeamsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TeamTeam)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTeamsIDNotFound creates a GetTeamsIDNotFound with default headers values
func NewGetTeamsIDNotFound() *GetTeamsIDNotFound {
	return &GetTeamsIDNotFound{}
}

/*
GetTeamsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetTeamsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get teams Id not found response has a 2xx status code
func (o *GetTeamsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get teams Id not found response has a 3xx status code
func (o *GetTeamsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get teams Id not found response has a 4xx status code
func (o *GetTeamsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get teams Id not found response has a 5xx status code
func (o *GetTeamsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get teams Id not found response a status code equal to that given
func (o *GetTeamsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get teams Id not found response
func (o *GetTeamsIDNotFound) Code() int {
	return 404
}

func (o *GetTeamsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdNotFound %s", 404, payload)
}

func (o *GetTeamsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdNotFound %s", 404, payload)
}

func (o *GetTeamsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetTeamsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetTeamsIDInternalServerError creates a GetTeamsIDInternalServerError with default headers values
func NewGetTeamsIDInternalServerError() *GetTeamsIDInternalServerError {
	return &GetTeamsIDInternalServerError{}
}

/*
GetTeamsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetTeamsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get teams Id internal server error response has a 2xx status code
func (o *GetTeamsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get teams Id internal server error response has a 3xx status code
func (o *GetTeamsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get teams Id internal server error response has a 4xx status code
func (o *GetTeamsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get teams Id internal server error response has a 5xx status code
func (o *GetTeamsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get teams Id internal server error response a status code equal to that given
func (o *GetTeamsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get teams Id internal server error response
func (o *GetTeamsIDInternalServerError) Code() int {
	return 500
}

func (o *GetTeamsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdInternalServerError %s", 500, payload)
}

func (o *GetTeamsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /teams/{id}][%d] getTeamsIdInternalServerError %s", 500, payload)
}

func (o *GetTeamsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetTeamsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
