// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostTeamsIDMembersUserIDConvertToManualReader is a Reader for the PostTeamsIDMembersUserIDConvertToManual structure.
type PostTeamsIDMembersUserIDConvertToManualReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTeamsIDMembersUserIDConvertToManualReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostTeamsIDMembersUserIDConvertToManualOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPostTeamsIDMembersUserIDConvertToManualNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostTeamsIDMembersUserIDConvertToManualInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /teams/{id}/members/{userId}/convert-to-manual] PostTeamsIDMembersUserIDConvertToManual", response, response.Code())
	}
}

// NewPostTeamsIDMembersUserIDConvertToManualOK creates a PostTeamsIDMembersUserIDConvertToManualOK with default headers values
func NewPostTeamsIDMembersUserIDConvertToManualOK() *PostTeamsIDMembersUserIDConvertToManualOK {
	return &PostTeamsIDMembersUserIDConvertToManualOK{}
}

/*
PostTeamsIDMembersUserIDConvertToManualOK describes a response with status code 200, with default header values.

OK
*/
type PostTeamsIDMembersUserIDConvertToManualOK struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this post teams Id members user Id convert to manual o k response has a 2xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post teams Id members user Id convert to manual o k response has a 3xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members user Id convert to manual o k response has a 4xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams Id members user Id convert to manual o k response has a 5xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members user Id convert to manual o k response a status code equal to that given
func (o *PostTeamsIDMembersUserIDConvertToManualOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post teams Id members user Id convert to manual o k response
func (o *PostTeamsIDMembersUserIDConvertToManualOK) Code() int {
	return 200
}

func (o *PostTeamsIDMembersUserIDConvertToManualOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualOK %s", 200, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualOK %s", 200, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualOK) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersUserIDConvertToManualOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersUserIDConvertToManualNotFound creates a PostTeamsIDMembersUserIDConvertToManualNotFound with default headers values
func NewPostTeamsIDMembersUserIDConvertToManualNotFound() *PostTeamsIDMembersUserIDConvertToManualNotFound {
	return &PostTeamsIDMembersUserIDConvertToManualNotFound{}
}

/*
PostTeamsIDMembersUserIDConvertToManualNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostTeamsIDMembersUserIDConvertToManualNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members user Id convert to manual not found response has a 2xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members user Id convert to manual not found response has a 3xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members user Id convert to manual not found response has a 4xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams Id members user Id convert to manual not found response has a 5xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members user Id convert to manual not found response a status code equal to that given
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post teams Id members user Id convert to manual not found response
func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) Code() int {
	return 404
}

func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualNotFound %s", 404, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualNotFound %s", 404, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersUserIDConvertToManualNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersUserIDConvertToManualInternalServerError creates a PostTeamsIDMembersUserIDConvertToManualInternalServerError with default headers values
func NewPostTeamsIDMembersUserIDConvertToManualInternalServerError() *PostTeamsIDMembersUserIDConvertToManualInternalServerError {
	return &PostTeamsIDMembersUserIDConvertToManualInternalServerError{}
}

/*
PostTeamsIDMembersUserIDConvertToManualInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostTeamsIDMembersUserIDConvertToManualInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members user Id convert to manual internal server error response has a 2xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members user Id convert to manual internal server error response has a 3xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members user Id convert to manual internal server error response has a 4xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams Id members user Id convert to manual internal server error response has a 5xx status code
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post teams Id members user Id convert to manual internal server error response a status code equal to that given
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post teams Id members user Id convert to manual internal server error response
func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) Code() int {
	return 500
}

func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualInternalServerError %s", 500, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members/{userId}/convert-to-manual][%d] postTeamsIdMembersUserIdConvertToManualInternalServerError %s", 500, payload)
}

func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersUserIDConvertToManualInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
