// Code generated by go-swagger; DO NOT EDIT.

package teams

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostTeamsReader is a Reader for the PostTeams structure.
type PostTeamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTeamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostTeamsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostTeamsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostTeamsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostTeamsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /teams] PostTeams", response, response.Code())
	}
}

// NewPostTeamsCreated creates a PostTeamsCreated with default headers values
func NewPostTeamsCreated() *PostTeamsCreated {
	return &PostTeamsCreated{}
}

/*
PostTeamsCreated describes a response with status code 201, with default header values.

Created
*/
type PostTeamsCreated struct {
	Payload *models.TeamTeam
}

// IsSuccess returns true when this post teams created response has a 2xx status code
func (o *PostTeamsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post teams created response has a 3xx status code
func (o *PostTeamsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams created response has a 4xx status code
func (o *PostTeamsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams created response has a 5xx status code
func (o *PostTeamsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams created response a status code equal to that given
func (o *PostTeamsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post teams created response
func (o *PostTeamsCreated) Code() int {
	return 201
}

func (o *PostTeamsCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsCreated %s", 201, payload)
}

func (o *PostTeamsCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsCreated %s", 201, payload)
}

func (o *PostTeamsCreated) GetPayload() *models.TeamTeam {
	return o.Payload
}

func (o *PostTeamsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TeamTeam)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsBadRequest creates a PostTeamsBadRequest with default headers values
func NewPostTeamsBadRequest() *PostTeamsBadRequest {
	return &PostTeamsBadRequest{}
}

/*
PostTeamsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostTeamsBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams bad request response has a 2xx status code
func (o *PostTeamsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams bad request response has a 3xx status code
func (o *PostTeamsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams bad request response has a 4xx status code
func (o *PostTeamsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams bad request response has a 5xx status code
func (o *PostTeamsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams bad request response a status code equal to that given
func (o *PostTeamsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post teams bad request response
func (o *PostTeamsBadRequest) Code() int {
	return 400
}

func (o *PostTeamsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsBadRequest %s", 400, payload)
}

func (o *PostTeamsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsBadRequest %s", 400, payload)
}

func (o *PostTeamsBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsConflict creates a PostTeamsConflict with default headers values
func NewPostTeamsConflict() *PostTeamsConflict {
	return &PostTeamsConflict{}
}

/*
PostTeamsConflict describes a response with status code 409, with default header values.

Conflict
*/
type PostTeamsConflict struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams conflict response has a 2xx status code
func (o *PostTeamsConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams conflict response has a 3xx status code
func (o *PostTeamsConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams conflict response has a 4xx status code
func (o *PostTeamsConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams conflict response has a 5xx status code
func (o *PostTeamsConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams conflict response a status code equal to that given
func (o *PostTeamsConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post teams conflict response
func (o *PostTeamsConflict) Code() int {
	return 409
}

func (o *PostTeamsConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsConflict %s", 409, payload)
}

func (o *PostTeamsConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsConflict %s", 409, payload)
}

func (o *PostTeamsConflict) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsInternalServerError creates a PostTeamsInternalServerError with default headers values
func NewPostTeamsInternalServerError() *PostTeamsInternalServerError {
	return &PostTeamsInternalServerError{}
}

/*
PostTeamsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostTeamsInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams internal server error response has a 2xx status code
func (o *PostTeamsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams internal server error response has a 3xx status code
func (o *PostTeamsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams internal server error response has a 4xx status code
func (o *PostTeamsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams internal server error response has a 5xx status code
func (o *PostTeamsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post teams internal server error response a status code equal to that given
func (o *PostTeamsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post teams internal server error response
func (o *PostTeamsInternalServerError) Code() int {
	return 500
}

func (o *PostTeamsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsInternalServerError %s", 500, payload)
}

func (o *PostTeamsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams][%d] postTeamsInternalServerError %s", 500, payload)
}

func (o *PostTeamsInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
