// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PostTeamsIDMembersReader is a Reader for the PostTeamsIDMembers structure.
type PostTeamsIDMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTeamsIDMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewPostTeamsIDMembersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostTeamsIDMembersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostTeamsIDMembersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostTeamsIDMembersConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostTeamsIDMembersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /teams/{id}/members] PostTeamsIDMembers", response, response.Code())
	}
}

// NewPostTeamsIDMembersCreated creates a PostTeamsIDMembersCreated with default headers values
func NewPostTeamsIDMembersCreated() *PostTeamsIDMembersCreated {
	return &PostTeamsIDMembersCreated{}
}

/*
PostTeamsIDMembersCreated describes a response with status code 201, with default header values.

Created
*/
type PostTeamsIDMembersCreated struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this post teams Id members created response has a 2xx status code
func (o *PostTeamsIDMembersCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post teams Id members created response has a 3xx status code
func (o *PostTeamsIDMembersCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members created response has a 4xx status code
func (o *PostTeamsIDMembersCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams Id members created response has a 5xx status code
func (o *PostTeamsIDMembersCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members created response a status code equal to that given
func (o *PostTeamsIDMembersCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post teams Id members created response
func (o *PostTeamsIDMembersCreated) Code() int {
	return 201
}

func (o *PostTeamsIDMembersCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersCreated %s", 201, payload)
}

func (o *PostTeamsIDMembersCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersCreated %s", 201, payload)
}

func (o *PostTeamsIDMembersCreated) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersBadRequest creates a PostTeamsIDMembersBadRequest with default headers values
func NewPostTeamsIDMembersBadRequest() *PostTeamsIDMembersBadRequest {
	return &PostTeamsIDMembersBadRequest{}
}

/*
PostTeamsIDMembersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostTeamsIDMembersBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members bad request response has a 2xx status code
func (o *PostTeamsIDMembersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members bad request response has a 3xx status code
func (o *PostTeamsIDMembersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members bad request response has a 4xx status code
func (o *PostTeamsIDMembersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams Id members bad request response has a 5xx status code
func (o *PostTeamsIDMembersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members bad request response a status code equal to that given
func (o *PostTeamsIDMembersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post teams Id members bad request response
func (o *PostTeamsIDMembersBadRequest) Code() int {
	return 400
}

func (o *PostTeamsIDMembersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersBadRequest %s", 400, payload)
}

func (o *PostTeamsIDMembersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersBadRequest %s", 400, payload)
}

func (o *PostTeamsIDMembersBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersForbidden creates a PostTeamsIDMembersForbidden with default headers values
func NewPostTeamsIDMembersForbidden() *PostTeamsIDMembersForbidden {
	return &PostTeamsIDMembersForbidden{}
}

/*
PostTeamsIDMembersForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostTeamsIDMembersForbidden struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members forbidden response has a 2xx status code
func (o *PostTeamsIDMembersForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members forbidden response has a 3xx status code
func (o *PostTeamsIDMembersForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members forbidden response has a 4xx status code
func (o *PostTeamsIDMembersForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams Id members forbidden response has a 5xx status code
func (o *PostTeamsIDMembersForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members forbidden response a status code equal to that given
func (o *PostTeamsIDMembersForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post teams Id members forbidden response
func (o *PostTeamsIDMembersForbidden) Code() int {
	return 403
}

func (o *PostTeamsIDMembersForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersForbidden %s", 403, payload)
}

func (o *PostTeamsIDMembersForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersForbidden %s", 403, payload)
}

func (o *PostTeamsIDMembersForbidden) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersConflict creates a PostTeamsIDMembersConflict with default headers values
func NewPostTeamsIDMembersConflict() *PostTeamsIDMembersConflict {
	return &PostTeamsIDMembersConflict{}
}

/*
PostTeamsIDMembersConflict describes a response with status code 409, with default header values.

Conflict
*/
type PostTeamsIDMembersConflict struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members conflict response has a 2xx status code
func (o *PostTeamsIDMembersConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members conflict response has a 3xx status code
func (o *PostTeamsIDMembersConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members conflict response has a 4xx status code
func (o *PostTeamsIDMembersConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post teams Id members conflict response has a 5xx status code
func (o *PostTeamsIDMembersConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post teams Id members conflict response a status code equal to that given
func (o *PostTeamsIDMembersConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post teams Id members conflict response
func (o *PostTeamsIDMembersConflict) Code() int {
	return 409
}

func (o *PostTeamsIDMembersConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersConflict %s", 409, payload)
}

func (o *PostTeamsIDMembersConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersConflict %s", 409, payload)
}

func (o *PostTeamsIDMembersConflict) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostTeamsIDMembersInternalServerError creates a PostTeamsIDMembersInternalServerError with default headers values
func NewPostTeamsIDMembersInternalServerError() *PostTeamsIDMembersInternalServerError {
	return &PostTeamsIDMembersInternalServerError{}
}

/*
PostTeamsIDMembersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostTeamsIDMembersInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this post teams Id members internal server error response has a 2xx status code
func (o *PostTeamsIDMembersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post teams Id members internal server error response has a 3xx status code
func (o *PostTeamsIDMembersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post teams Id members internal server error response has a 4xx status code
func (o *PostTeamsIDMembersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post teams Id members internal server error response has a 5xx status code
func (o *PostTeamsIDMembersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post teams Id members internal server error response a status code equal to that given
func (o *PostTeamsIDMembersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post teams Id members internal server error response
func (o *PostTeamsIDMembersInternalServerError) Code() int {
	return 500
}

func (o *PostTeamsIDMembersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersInternalServerError %s", 500, payload)
}

func (o *PostTeamsIDMembersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /teams/{id}/members][%d] postTeamsIdMembersInternalServerError %s", 500, payload)
}

func (o *PostTeamsIDMembersInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PostTeamsIDMembersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
