// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PutTeamsIDReader is a Reader for the PutTeamsID structure.
type PutTeamsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTeamsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutTeamsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutTeamsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutTeamsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutTeamsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutTeamsIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutTeamsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /teams/{id}] PutTeamsID", response, response.Code())
	}
}

// NewPutTeamsIDOK creates a PutTeamsIDOK with default headers values
func NewPutTeamsIDOK() *PutTeamsIDOK {
	return &PutTeamsIDOK{}
}

/*
PutTeamsIDOK describes a response with status code 200, with default header values.

OK
*/
type PutTeamsIDOK struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this put teams Id o k response has a 2xx status code
func (o *PutTeamsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put teams Id o k response has a 3xx status code
func (o *PutTeamsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id o k response has a 4xx status code
func (o *PutTeamsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put teams Id o k response has a 5xx status code
func (o *PutTeamsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id o k response a status code equal to that given
func (o *PutTeamsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put teams Id o k response
func (o *PutTeamsIDOK) Code() int {
	return 200
}

func (o *PutTeamsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdOK %s", 200, payload)
}

func (o *PutTeamsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdOK %s", 200, payload)
}

func (o *PutTeamsIDOK) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *PutTeamsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDBadRequest creates a PutTeamsIDBadRequest with default headers values
func NewPutTeamsIDBadRequest() *PutTeamsIDBadRequest {
	return &PutTeamsIDBadRequest{}
}

/*
PutTeamsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutTeamsIDBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id bad request response has a 2xx status code
func (o *PutTeamsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id bad request response has a 3xx status code
func (o *PutTeamsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id bad request response has a 4xx status code
func (o *PutTeamsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id bad request response has a 5xx status code
func (o *PutTeamsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id bad request response a status code equal to that given
func (o *PutTeamsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put teams Id bad request response
func (o *PutTeamsIDBadRequest) Code() int {
	return 400
}

func (o *PutTeamsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdBadRequest %s", 400, payload)
}

func (o *PutTeamsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdBadRequest %s", 400, payload)
}

func (o *PutTeamsIDBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDForbidden creates a PutTeamsIDForbidden with default headers values
func NewPutTeamsIDForbidden() *PutTeamsIDForbidden {
	return &PutTeamsIDForbidden{}
}

/*
PutTeamsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutTeamsIDForbidden struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id forbidden response has a 2xx status code
func (o *PutTeamsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id forbidden response has a 3xx status code
func (o *PutTeamsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id forbidden response has a 4xx status code
func (o *PutTeamsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id forbidden response has a 5xx status code
func (o *PutTeamsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id forbidden response a status code equal to that given
func (o *PutTeamsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put teams Id forbidden response
func (o *PutTeamsIDForbidden) Code() int {
	return 403
}

func (o *PutTeamsIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdForbidden %s", 403, payload)
}

func (o *PutTeamsIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdForbidden %s", 403, payload)
}

func (o *PutTeamsIDForbidden) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDNotFound creates a PutTeamsIDNotFound with default headers values
func NewPutTeamsIDNotFound() *PutTeamsIDNotFound {
	return &PutTeamsIDNotFound{}
}

/*
PutTeamsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutTeamsIDNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id not found response has a 2xx status code
func (o *PutTeamsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id not found response has a 3xx status code
func (o *PutTeamsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id not found response has a 4xx status code
func (o *PutTeamsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id not found response has a 5xx status code
func (o *PutTeamsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id not found response a status code equal to that given
func (o *PutTeamsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put teams Id not found response
func (o *PutTeamsIDNotFound) Code() int {
	return 404
}

func (o *PutTeamsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdNotFound %s", 404, payload)
}

func (o *PutTeamsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdNotFound %s", 404, payload)
}

func (o *PutTeamsIDNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDConflict creates a PutTeamsIDConflict with default headers values
func NewPutTeamsIDConflict() *PutTeamsIDConflict {
	return &PutTeamsIDConflict{}
}

/*
PutTeamsIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutTeamsIDConflict struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id conflict response has a 2xx status code
func (o *PutTeamsIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id conflict response has a 3xx status code
func (o *PutTeamsIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id conflict response has a 4xx status code
func (o *PutTeamsIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id conflict response has a 5xx status code
func (o *PutTeamsIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id conflict response a status code equal to that given
func (o *PutTeamsIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put teams Id conflict response
func (o *PutTeamsIDConflict) Code() int {
	return 409
}

func (o *PutTeamsIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdConflict %s", 409, payload)
}

func (o *PutTeamsIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdConflict %s", 409, payload)
}

func (o *PutTeamsIDConflict) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDInternalServerError creates a PutTeamsIDInternalServerError with default headers values
func NewPutTeamsIDInternalServerError() *PutTeamsIDInternalServerError {
	return &PutTeamsIDInternalServerError{}
}

/*
PutTeamsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutTeamsIDInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id internal server error response has a 2xx status code
func (o *PutTeamsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id internal server error response has a 3xx status code
func (o *PutTeamsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id internal server error response has a 4xx status code
func (o *PutTeamsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put teams Id internal server error response has a 5xx status code
func (o *PutTeamsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put teams Id internal server error response a status code equal to that given
func (o *PutTeamsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put teams Id internal server error response
func (o *PutTeamsIDInternalServerError) Code() int {
	return 500
}

func (o *PutTeamsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdInternalServerError %s", 500, payload)
}

func (o *PutTeamsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}][%d] putTeamsIdInternalServerError %s", 500, payload)
}

func (o *PutTeamsIDInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
