// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// PutTeamsIDMembersUserIDRoleReader is a Reader for the PutTeamsIDMembersUserIDRole structure.
type PutTeamsIDMembersUserIDRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutTeamsIDMembersUserIDRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutTeamsIDMembersUserIDRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutTeamsIDMembersUserIDRoleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutTeamsIDMembersUserIDRoleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutTeamsIDMembersUserIDRoleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /teams/{id}/members/{userId}/role] PutTeamsIDMembersUserIDRole", response, response.Code())
	}
}

// NewPutTeamsIDMembersUserIDRoleOK creates a PutTeamsIDMembersUserIDRoleOK with default headers values
func NewPutTeamsIDMembersUserIDRoleOK() *PutTeamsIDMembersUserIDRoleOK {
	return &PutTeamsIDMembersUserIDRoleOK{}
}

/*
PutTeamsIDMembersUserIDRoleOK describes a response with status code 200, with default header values.

OK
*/
type PutTeamsIDMembersUserIDRoleOK struct {
	Payload *models.V1TeamsMessageResponse
}

// IsSuccess returns true when this put teams Id members user Id role o k response has a 2xx status code
func (o *PutTeamsIDMembersUserIDRoleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put teams Id members user Id role o k response has a 3xx status code
func (o *PutTeamsIDMembersUserIDRoleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id members user Id role o k response has a 4xx status code
func (o *PutTeamsIDMembersUserIDRoleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put teams Id members user Id role o k response has a 5xx status code
func (o *PutTeamsIDMembersUserIDRoleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id members user Id role o k response a status code equal to that given
func (o *PutTeamsIDMembersUserIDRoleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put teams Id members user Id role o k response
func (o *PutTeamsIDMembersUserIDRoleOK) Code() int {
	return 200
}

func (o *PutTeamsIDMembersUserIDRoleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleOK %s", 200, payload)
}

func (o *PutTeamsIDMembersUserIDRoleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleOK %s", 200, payload)
}

func (o *PutTeamsIDMembersUserIDRoleOK) GetPayload() *models.V1TeamsMessageResponse {
	return o.Payload
}

func (o *PutTeamsIDMembersUserIDRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TeamsMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDMembersUserIDRoleBadRequest creates a PutTeamsIDMembersUserIDRoleBadRequest with default headers values
func NewPutTeamsIDMembersUserIDRoleBadRequest() *PutTeamsIDMembersUserIDRoleBadRequest {
	return &PutTeamsIDMembersUserIDRoleBadRequest{}
}

/*
PutTeamsIDMembersUserIDRoleBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutTeamsIDMembersUserIDRoleBadRequest struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id members user Id role bad request response has a 2xx status code
func (o *PutTeamsIDMembersUserIDRoleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id members user Id role bad request response has a 3xx status code
func (o *PutTeamsIDMembersUserIDRoleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id members user Id role bad request response has a 4xx status code
func (o *PutTeamsIDMembersUserIDRoleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id members user Id role bad request response has a 5xx status code
func (o *PutTeamsIDMembersUserIDRoleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id members user Id role bad request response a status code equal to that given
func (o *PutTeamsIDMembersUserIDRoleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put teams Id members user Id role bad request response
func (o *PutTeamsIDMembersUserIDRoleBadRequest) Code() int {
	return 400
}

func (o *PutTeamsIDMembersUserIDRoleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleBadRequest %s", 400, payload)
}

func (o *PutTeamsIDMembersUserIDRoleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleBadRequest %s", 400, payload)
}

func (o *PutTeamsIDMembersUserIDRoleBadRequest) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDMembersUserIDRoleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDMembersUserIDRoleNotFound creates a PutTeamsIDMembersUserIDRoleNotFound with default headers values
func NewPutTeamsIDMembersUserIDRoleNotFound() *PutTeamsIDMembersUserIDRoleNotFound {
	return &PutTeamsIDMembersUserIDRoleNotFound{}
}

/*
PutTeamsIDMembersUserIDRoleNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutTeamsIDMembersUserIDRoleNotFound struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id members user Id role not found response has a 2xx status code
func (o *PutTeamsIDMembersUserIDRoleNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id members user Id role not found response has a 3xx status code
func (o *PutTeamsIDMembersUserIDRoleNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id members user Id role not found response has a 4xx status code
func (o *PutTeamsIDMembersUserIDRoleNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put teams Id members user Id role not found response has a 5xx status code
func (o *PutTeamsIDMembersUserIDRoleNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put teams Id members user Id role not found response a status code equal to that given
func (o *PutTeamsIDMembersUserIDRoleNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put teams Id members user Id role not found response
func (o *PutTeamsIDMembersUserIDRoleNotFound) Code() int {
	return 404
}

func (o *PutTeamsIDMembersUserIDRoleNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleNotFound %s", 404, payload)
}

func (o *PutTeamsIDMembersUserIDRoleNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleNotFound %s", 404, payload)
}

func (o *PutTeamsIDMembersUserIDRoleNotFound) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDMembersUserIDRoleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutTeamsIDMembersUserIDRoleInternalServerError creates a PutTeamsIDMembersUserIDRoleInternalServerError with default headers values
func NewPutTeamsIDMembersUserIDRoleInternalServerError() *PutTeamsIDMembersUserIDRoleInternalServerError {
	return &PutTeamsIDMembersUserIDRoleInternalServerError{}
}

/*
PutTeamsIDMembersUserIDRoleInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PutTeamsIDMembersUserIDRoleInternalServerError struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this put teams Id members user Id role internal server error response has a 2xx status code
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put teams Id members user Id role internal server error response has a 3xx status code
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put teams Id members user Id role internal server error response has a 4xx status code
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put teams Id members user Id role internal server error response has a 5xx status code
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put teams Id members user Id role internal server error response a status code equal to that given
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put teams Id members user Id role internal server error response
func (o *PutTeamsIDMembersUserIDRoleInternalServerError) Code() int {
	return 500
}

func (o *PutTeamsIDMembersUserIDRoleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleInternalServerError %s", 500, payload)
}

func (o *PutTeamsIDMembersUserIDRoleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /teams/{id}/members/{userId}/role][%d] putTeamsIdMembersUserIdRoleInternalServerError %s", 500, payload)
}

func (o *PutTeamsIDMembersUserIDRoleInternalServerError) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *PutTeamsIDMembersUserIDRoleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
