// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new teams API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new teams API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new teams API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for teams API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteTeamsID(params *DeleteTeamsIDParams, opts ...ClientOption) (*DeleteTeamsIDOK, error)

	DeleteTeamsIDMembersUserID(params *DeleteTeamsIDMembersUserIDParams, opts ...ClientOption) (*DeleteTeamsIDMembersUserIDOK, error)

	GetTeams(params *GetTeamsParams, opts ...ClientOption) (*GetTeamsOK, error)

	GetTeamsID(params *GetTeamsIDParams, opts ...ClientOption) (*GetTeamsIDOK, error)

	GetTeamsIDMembers(params *GetTeamsIDMembersParams, opts ...ClientOption) (*GetTeamsIDMembersOK, error)

	PostTeams(params *PostTeamsParams, opts ...ClientOption) (*PostTeamsCreated, error)

	PostTeamsIDMembers(params *PostTeamsIDMembersParams, opts ...ClientOption) (*PostTeamsIDMembersCreated, error)

	PostTeamsIDMembersUserIDConvertToManual(params *PostTeamsIDMembersUserIDConvertToManualParams, opts ...ClientOption) (*PostTeamsIDMembersUserIDConvertToManualOK, error)

	PutTeamsID(params *PutTeamsIDParams, opts ...ClientOption) (*PutTeamsIDOK, error)

	PutTeamsIDMembersUserIDRole(params *PutTeamsIDMembersUserIDRoleParams, opts ...ClientOption) (*PutTeamsIDMembersUserIDRoleOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteTeamsID deletes a team

Delete a team by its ID
*/
func (a *Client) DeleteTeamsID(params *DeleteTeamsIDParams, opts ...ClientOption) (*DeleteTeamsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteTeamsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeamsID",
		Method:             "DELETE",
		PathPattern:        "/teams/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteTeamsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteTeamsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteTeamsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteTeamsIDMembersUserID removes a team member

Remove a user from a team
*/
func (a *Client) DeleteTeamsIDMembersUserID(params *DeleteTeamsIDMembersUserIDParams, opts ...ClientOption) (*DeleteTeamsIDMembersUserIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteTeamsIDMembersUserIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeamsIDMembersUserID",
		Method:             "DELETE",
		PathPattern:        "/teams/{id}/members/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteTeamsIDMembersUserIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteTeamsIDMembersUserIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteTeamsIDMembersUserID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTeams lists teams

Get a paginated list of teams
*/
func (a *Client) GetTeams(params *GetTeamsParams, opts ...ClientOption) (*GetTeamsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTeamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetTeams",
		Method:             "GET",
		PathPattern:        "/teams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTeamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTeamsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetTeams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTeamsID gets a team

Get a team by its ID
*/
func (a *Client) GetTeamsID(params *GetTeamsIDParams, opts ...ClientOption) (*GetTeamsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTeamsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetTeamsID",
		Method:             "GET",
		PathPattern:        "/teams/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTeamsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTeamsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetTeamsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetTeamsIDMembers lists team members

Get the members of a team
*/
func (a *Client) GetTeamsIDMembers(params *GetTeamsIDMembersParams, opts ...ClientOption) (*GetTeamsIDMembersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetTeamsIDMembersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetTeamsIDMembers",
		Method:             "GET",
		PathPattern:        "/teams/{id}/members",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetTeamsIDMembersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetTeamsIDMembersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetTeamsIDMembers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostTeams creates a team

Create a new team
*/
func (a *Client) PostTeams(params *PostTeamsParams, opts ...ClientOption) (*PostTeamsCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostTeamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostTeams",
		Method:             "POST",
		PathPattern:        "/teams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostTeamsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostTeamsCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostTeams: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostTeamsIDMembers adds a team member

Add a user as a member of a team
*/
func (a *Client) PostTeamsIDMembers(params *PostTeamsIDMembersParams, opts ...ClientOption) (*PostTeamsIDMembersCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostTeamsIDMembersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostTeamsIDMembers",
		Method:             "POST",
		PathPattern:        "/teams/{id}/members",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostTeamsIDMembersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostTeamsIDMembersCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostTeamsIDMembers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostTeamsIDMembersUserIDConvertToManual converts member to manual

Convert an SSO-managed team member to a manually managed member
*/
func (a *Client) PostTeamsIDMembersUserIDConvertToManual(params *PostTeamsIDMembersUserIDConvertToManualParams, opts ...ClientOption) (*PostTeamsIDMembersUserIDConvertToManualOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostTeamsIDMembersUserIDConvertToManualParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostTeamsIDMembersUserIDConvertToManual",
		Method:             "POST",
		PathPattern:        "/teams/{id}/members/{userId}/convert-to-manual",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostTeamsIDMembersUserIDConvertToManualReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostTeamsIDMembersUserIDConvertToManualOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostTeamsIDMembersUserIDConvertToManual: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutTeamsID updates a team

Update a team's fields by its ID
*/
func (a *Client) PutTeamsID(params *PutTeamsIDParams, opts ...ClientOption) (*PutTeamsIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutTeamsIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutTeamsID",
		Method:             "PUT",
		PathPattern:        "/teams/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutTeamsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutTeamsIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutTeamsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutTeamsIDMembersUserIDRole updates member role

Update the role of a team member
*/
func (a *Client) PutTeamsIDMembersUserIDRole(params *PutTeamsIDMembersUserIDRoleParams, opts ...ClientOption) (*PutTeamsIDMembersUserIDRoleOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutTeamsIDMembersUserIDRoleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutTeamsIDMembersUserIDRole",
		Method:             "PUT",
		PathPattern:        "/teams/{id}/members/{userId}/role",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutTeamsIDMembersUserIDRoleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutTeamsIDMembersUserIDRoleOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutTeamsIDMembersUserIDRole: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
