// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/marmotdata/marmot/client/models"
)

// GetAdminSearchReindexReader is a Reader for the GetAdminSearchReindex structure.
type GetAdminSearchReindexReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdminSearchReindexReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAdminSearchReindexOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAdminSearchReindexUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAdminSearchReindexForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /admin/search/reindex] GetAdminSearchReindex", response, response.Code())
	}
}

// NewGetAdminSearchReindexOK creates a GetAdminSearchReindexOK with default headers values
func NewGetAdminSearchReindexOK() *GetAdminSearchReindexOK {
	return &GetAdminSearchReindexOK{}
}

/*
GetAdminSearchReindexOK describes a response with status code 200, with default header values.

OK
*/
type GetAdminSearchReindexOK struct {
	Payload *models.V1AdminReindexStatusResponse
}

// IsSuccess returns true when this get admin search reindex o k response has a 2xx status code
func (o *GetAdminSearchReindexOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get admin search reindex o k response has a 3xx status code
func (o *GetAdminSearchReindexOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get admin search reindex o k response has a 4xx status code
func (o *GetAdminSearchReindexOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get admin search reindex o k response has a 5xx status code
func (o *GetAdminSearchReindexOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get admin search reindex o k response a status code equal to that given
func (o *GetAdminSearchReindexOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get admin search reindex o k response
func (o *GetAdminSearchReindexOK) Code() int {
	return 200
}

func (o *GetAdminSearchReindexOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexOK %s", 200, payload)
}

func (o *GetAdminSearchReindexOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexOK %s", 200, payload)
}

func (o *GetAdminSearchReindexOK) GetPayload() *models.V1AdminReindexStatusResponse {
	return o.Payload
}

func (o *GetAdminSearchReindexOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1AdminReindexStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAdminSearchReindexUnauthorized creates a GetAdminSearchReindexUnauthorized with default headers values
func NewGetAdminSearchReindexUnauthorized() *GetAdminSearchReindexUnauthorized {
	return &GetAdminSearchReindexUnauthorized{}
}

/*
GetAdminSearchReindexUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAdminSearchReindexUnauthorized struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get admin search reindex unauthorized response has a 2xx status code
func (o *GetAdminSearchReindexUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get admin search reindex unauthorized response has a 3xx status code
func (o *GetAdminSearchReindexUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get admin search reindex unauthorized response has a 4xx status code
func (o *GetAdminSearchReindexUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get admin search reindex unauthorized response has a 5xx status code
func (o *GetAdminSearchReindexUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get admin search reindex unauthorized response a status code equal to that given
func (o *GetAdminSearchReindexUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get admin search reindex unauthorized response
func (o *GetAdminSearchReindexUnauthorized) Code() int {
	return 401
}

func (o *GetAdminSearchReindexUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexUnauthorized %s", 401, payload)
}

func (o *GetAdminSearchReindexUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexUnauthorized %s", 401, payload)
}

func (o *GetAdminSearchReindexUnauthorized) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAdminSearchReindexUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAdminSearchReindexForbidden creates a GetAdminSearchReindexForbidden with default headers values
func NewGetAdminSearchReindexForbidden() *GetAdminSearchReindexForbidden {
	return &GetAdminSearchReindexForbidden{}
}

/*
GetAdminSearchReindexForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAdminSearchReindexForbidden struct {
	Payload *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse
}

// IsSuccess returns true when this get admin search reindex forbidden response has a 2xx status code
func (o *GetAdminSearchReindexForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get admin search reindex forbidden response has a 3xx status code
func (o *GetAdminSearchReindexForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get admin search reindex forbidden response has a 4xx status code
func (o *GetAdminSearchReindexForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get admin search reindex forbidden response has a 5xx status code
func (o *GetAdminSearchReindexForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get admin search reindex forbidden response a status code equal to that given
func (o *GetAdminSearchReindexForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get admin search reindex forbidden response
func (o *GetAdminSearchReindexForbidden) Code() int {
	return 403
}

func (o *GetAdminSearchReindexForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexForbidden %s", 403, payload)
}

func (o *GetAdminSearchReindexForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/search/reindex][%d] getAdminSearchReindexForbidden %s", 403, payload)
}

func (o *GetAdminSearchReindexForbidden) GetPayload() *models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse {
	return o.Payload
}

func (o *GetAdminSearchReindexForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComMarmotdataMarmotInternalAPIV1CommonErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
