name: Prow PR jobs

on:
  pull_request:
    types: [synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: cncf/prow-github-actions@c44ac3a57d67639e39e4a4988b52049ef45b80dd
        with:
          github-token: ${{ secrets.PROW_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          jobs: lgtm
