name: Prow PR jobs

on:
  pull_request:
    types: [synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: cncf/prow-github-actions@187c5e3cd95a329c43448e1bdb3b1f5249232e44
        with:
          github-token: ${{ secrets.PROW_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          jobs: lgtm
