name: Prow commands (open)

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    if: >-
      github.event.comment.user.type != 'Bot' && (
        contains(github.event.comment.body, '/assign') ||
        contains(github.event.comment.body, '/unassign') ||
        contains(github.event.comment.body, '/cc') ||
        contains(github.event.comment.body, '/uncc')
      )
    steps:
      - uses: cncf/prow-github-actions@c44ac3a57d67639e39e4a4988b52049ef45b80dd
        with:
          github-token: ${{ secrets.PROW_BOT_TOKEN || secrets.GITHUB_TOKEN }}
          prow-commands: |
            /assign
            /unassign
            /cc
            /uncc
