<script lang="ts">
	import { fetchApi } from '$lib/api';
	import type { Asset } from '$lib/assets/types';
	import { auth } from '$lib/stores/auth';

	let { asset, editable = true }: { asset: Asset; editable?: boolean } = $props();

	let canManageAssets = $derived(editable && auth.hasPermission('assets', 'manage'));

	let userDescription = $state(asset?.user_description || '');
	let isEditingUserDesc = $state(false);
	let savingUserDesc = $state(false);

	$effect(() => {
		if (asset?.user_description !== undefined) {
			userDescription = asset.user_description || '';
		}
	});

	async function saveUserDescription() {
		if (!asset?.id) return;

		savingUserDesc = true;
		try {
			const response = await fetchApi(`/assets/${asset.id}`, {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					user_description: userDescription.trim() || null
				})
			});

			if (response.ok) {
				asset.user_description = userDescription.trim() || undefined;
				isEditingUserDesc = false;
			} else {
				console.error('Failed to save user description');
			}
		} catch (error) {
			console.error('Error saving user description:', error);
		} finally {
			savingUserDesc = false;
		}
	}

	function cancelEdit() {
		userDescription = asset.user_description || '';
		isEditingUserDesc = false;
	}
</script>

<div class="space-y-5">
	<!-- Technical Description (from plugins) -->
	{#if asset.description}
		<div>
			<div class="flex items-center gap-2 mb-2">
				<h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">
					Technical Description
				</h3>
				<div
					class="flex items-center justify-center w-5 h-5 rounded-full bg-purple-100 dark:bg-purple-900/30"
					title="Generated by plugin"
				>
					<svg
						class="w-3 h-3 text-purple-700 dark:text-purple-300"
						fill="currentColor"
						viewBox="0 0 20 20"
					>
						<path
							fill-rule="evenodd"
							d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z"
							clip-rule="evenodd"
						/>
					</svg>
				</div>
			</div>
			<p class="text-sm text-gray-600 dark:text-gray-400 whitespace-pre-wrap leading-relaxed">
				{asset.description}
			</p>
		</div>
	{/if}

	<!-- User Description (manual notes) -->
	{#if asset.user_description || canManageAssets}
		<div>
			<div class="flex items-center justify-between mb-2">
				<div class="flex items-center gap-2">
					<h3 class="text-base font-semibold text-gray-900 dark:text-gray-100">User Notes</h3>
					<div
						class="flex items-center justify-center w-5 h-5 rounded-full bg-blue-100 dark:bg-blue-900/30"
						title="Manually added by user"
					>
						<svg
							class="w-3 h-3 text-blue-700 dark:text-blue-300"
							fill="currentColor"
							viewBox="0 0 20 20"
						>
							<path
								fill-rule="evenodd"
								d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
								clip-rule="evenodd"
							/>
						</svg>
					</div>
				</div>
				{#if canManageAssets && !isEditingUserDesc}
					<button
						onclick={() => (isEditingUserDesc = true)}
						class="text-sm text-orange-600 dark:text-orange-400 hover:text-orange-700 dark:hover:text-orange-300 font-medium"
					>
						{asset.user_description ? 'Edit' : '+ Add'}
					</button>
				{/if}
			</div>

			{#if isEditingUserDesc}
				<div class="space-y-2.5">
					<textarea
						bind:value={userDescription}
						placeholder="Add your notes..."
						rows="4"
						class="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-orange-500 focus:border-transparent resize-y"
					></textarea>
					<div class="flex justify-end gap-2">
						<button
							onclick={cancelEdit}
							disabled={savingUserDesc}
							class="px-3 py-1.5 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded disabled:opacity-50"
						>
							Cancel
						</button>
						<button
							onclick={saveUserDescription}
							disabled={savingUserDesc}
							class="px-3 py-1.5 text-sm bg-orange-600 text-white rounded hover:bg-orange-700 disabled:opacity-50 flex items-center gap-1.5"
						>
							{#if savingUserDesc}
								<div class="animate-spin rounded-full h-3 w-3 border-b-2 border-white"></div>
							{/if}
							Save
						</button>
					</div>
				</div>
			{:else if asset.user_description}
				<p class="text-sm text-gray-600 dark:text-gray-400 whitespace-pre-wrap leading-relaxed">
					{asset.user_description}
				</p>
			{:else}
				<p class="text-sm text-gray-500 dark:text-gray-400 italic">No notes yet</p>
			{/if}
		</div>
	{/if}
</div>
